### ISSUE TITLE
Unable to use software

### ISSUE THREAD

**Issue by blawalt** [dheijl/swyh-rs#103]
I apologize as I'm pretty new to the IT world, I am just not familiar with how to run this. I was hoping by opening an issue you'd maybe be able to help me? Otherwise please feel free to close out. I feel like I'm supposed to be using the .iss file, and I downloaded Inno Setup compiler, but nothing is working for me. I welcome any assistance. I'm being told that the .exe file is not present (which is a true statement) and I don't know what to do to remedy that

**Comment by dheijl** [comment]
Just go to "Releases", select the latest one, download the setup, unzip and run it.
Direct link: [latest setup zip](https://github.com/dheijl/swyh-rs/releases/download/1.8.3/Setup-swyh-rs.zip).

**Comment by blawalt** [comment]
I guess I don’t understand what you mean by “run it”. I don’t see any
executable files in the zip

**Comment by dheijl** [comment]
Perhaps some anti-virus software on your pc or on your network is blocking it or stripping the contents of the zip.
I'm afraid I can't help you with that.
