### ISSUE TITLE
How to install swyh-rs on Moode Audio OS (Raspberry Pi 2)

### ISSUE THREAD

**Issue by luna800** [dheijl/swyh-rs#105]
if you are not an expert, is there a guide to follow?

**Comment by dheijl** [comment]
I'm afraid you will have to build from source, either on a raspberry pi or using cross-compilation (I have no experience with rust on a raspberry pi).
Also, as Moode does not have a graphical desktop installed, you will only be able to use the cli version, swyh-rs-cli.
Have you considered alternatives available on Linux, like pulseaudio-dlna? (But I don't know if pulseaudio-dlna is available in the raspberry pi repos).
