### ISSUE TITLE
Considerable delay when streaming from PC (Windows)

### ISSUE THREAD

**Issue by jamilg** [dheijl/swyh-rs#106]
First of all, thanks for the app. It works great so far.
The only think that bugs me is that there is a noticeable delay (10-15 secs) between when I press play in browser (i.e. SoundCloud) and the sound starting/stopping.
I am using Raspberry Pi 3B with Moode 8 as a Upnp renderer over wifi.
Audio format of the stream is FLAC 24bit.
I am not sure if it is supposed to be like this. Is it architectural constraints or implementation?

**Comment by dheijl** [comment]
Possible sources of delay are:

- buffering inside swyh-rs for http streaming: 8 KB
- buffering inside the flac compressor and decompressor: variable depending on the music and the bitrate
- buffering inside moode upnp: not configurable from UI
- buffering by MPD: configured in the mpd config file and partly in the moode UI for MPD
- buffering by the wifi hardware

I suppose that flac compression causes the biggest delay, you can verify this by switching to wav 16 bit 44 khz (CD quality).

**Comment by jamilg** [comment]
Thanks for response.
It seems, in my case the audio source was the case. Switched to youtube music and delay is merely one second most kf the times. Must be SoundCloud track quality was too much.
