### ISSUE TITLE
Streaming has ended

### ISSUE THREAD

**Issue by mattenausohz** [dheijl/swyh-rs#109]
Hallo! 

Can someone please help? I am getting the following most of the time: 

--
Configuration { server_port: Some(5901), auto_resume: false, sound_source: "Speakers/Headphones (Realtek(R) Audio)", sound_source_index: Some(0), log_level: Debug, ssdp_interval_mins: 10.0, auto_reconnect: true, disable_chunked: true, use_wave_format: false, bits_per_sample: Some(16), streaming_format: Some(Lpcm), monitor_rms: true, capture_timeout: Some(2000), inject_silence: Some(false), last_renderer: "UpMPD Volumio", last_network: "192.168.188.50", config_dir: "C:\\Users\\DATEVasp\\.swyh-rs", config_id: Some("") }
Setup audio sources
Now running at ABOVE_NORMAL_PRIORITY_CLASS
Capturing audio from: Speakers/Headphones (Realtek(R) Audio)
Default audio SupportedStreamConfig { channels: 2, sample_rate: SampleRate(48000), buffer_size: Range { min: 0, max: 4294967295 }, sample_format: F32 }
Discover networks
Starting SSDP discovery
The streaming server is listening on http://192.168.188.50:5901/stream/swyh.wav
Streaming sample rate: 48000, bits per sample: 16, format: LPCM
The wave_reader is now receiving samples
OH Start playing on Volumio host=192.168.188.64 port=49152 from 192.168.188.50 using OpenHome Playlist
OH Deleting current playlist on Volumio host=192.168.188.64 port=49152
OH Inserting new playlist on Volumio host=192.168.188.64 port=49152
OH Play on Volumio host=192.168.188.64 port=49152
Received request /stream/swyh.wav from 192.168.188.64:57094
Streaming audio/L16 (LPCM), input sample format F32, channels=2, rate=48000, disable chunked=true to 192.168.188.64:57094
Received request /stream/swyh.wav from 192.168.188.64:57096
Streaming audio/L16 (LPCM), input sample format F32, channels=2, rate=48000, disable chunked=true to 192.168.188.64:57096
Streaming to 192.168.188.64:57094 has ended
--

**Comment by dheijl** [comment]
Have you tried FLAC or WAV instead of LPCM format? Older Volumio versions did not support streaming WAV due to outdated libraries, but this may have changed. Current versions of Moode for instance only support WAV and FLAC.
I no longer use Volumio, so unfortunately I can't try to reproduce your problem.
You might be able to get more info about why the streaming ends by looking at the MPD logs on the Volumio side.

**Comment by dheijl** [comment]
You could try the latest release [1.8.7](https://github.com/dheijl/swyh-rs/releases/tag/1.8.7), it fixes some WAV and LPCM issues with MPD as used by Volumio and MoodeAudio.
