### ISSUE TITLE
[CLI] Serve-only mode (don't search for or connect to renderers)

### ISSUE THREAD

**Issue by instinctualjealousy** [dheijl/swyh-rs#111]
Allow swyh-rs-cli to simply host the audio on the defined port, without trying to stream it to a media renderer (and terminating with an error if none are found). This could be achieved with an argument.

**Comment by dheijl** [comment]
Can you try the [new beta](https://github.com/dheijl/swyh-rs/releases/tag/1.9.2-beta) with the new **-x** (--serve_only) option?

**Comment by instinctualjealousy** [comment]
![image](https://github.com/dheijl/swyh-rs/assets/13276804/28646362-9889-464e-a5f5-00ac87b798b6)
I also tried -x and --serve`_`only, like mentioned above. Program doesn't seem to be registering it judging on the Args report, and I still get the same "No renderers found!!!" Error -1. Does the argument need an option like "true" or "yes"?

**Comment by dheijl** [comment]
-x true or --serve_only true, argument indeed required.
I could change it to -x without argument meaning true and -x absent meaning false, but all other arguments (except -n and -h) need the argument.

**Comment by instinctualjealousy** [comment]
After I passed the argument correctly, it's working. Xbox 360 connects to foobar UPnP, I choose my swyh.wav entry, and swyh-rs confirms a connection and provides audio as expected. I think I prefer "without argument meaning true" in this case, but it's a very minor thing.

**Comment by dheijl** [comment]
[beta2](https://github.com/dheijl/swyh-rs/releases/tag/1.9.2-beta2) no longer needs the extra argument.

If you're satisfied I'll release 1.9.2.

**Comment by instinctualjealousy** [comment]
Absolutely, thank you for your assistance and quick changes. =)
