### ISSUE TITLE
[QUESTION] How can I achieve best possible lag freee / 0 latency when streaming audio from PC to Wifi Speaker

### ISSUE THREAD

**Issue by YHSX88** [dheijl/swyh-rs#121]
hey the title says it all. Thanks for all suggestion.
Feel free to throw any suggestion from changing the router to new sound card :D 

My setup now is:

PC connected to gigabit router via LAN streams music via sound card ALC1220S ->>> Denon Home 150 connected to the same network via LAN.

and I get 1-2 secs delay/latency

Thanks

**Comment by dheijl** [comment]
I'm afraid there's nothing you can do to shorten the delay introduced by the network, receiver buffering and FLAC compression (if you use flac).

Your only option is to connect he soundcard directly to the Denon (not using swyh-rs at all).

YHSX88 ***@***.***> schreef op 27 februari 2024 07:56:11 CET:
