### ISSUE TITLE
Changing Audio-Source Index

### ISSUE THREAD

**Issue by benkra66** [dheijl/swyh-rs#122]
Hello, first of all, love youre software. I mainly use it for streaming PC-audio to my volumio Server and it covers all of my bases.
In the last few weeks i came across a minor Issue where the Source-Index of Windows (Audio-Source) shifts whenever a device is connected and disconnected. Which is, for as long as i am concernt, the way it should be.
My problem is that this behavior breaks my script everytime i plug in a device that is typically not part of my setup.

In the config_cli.toml i saw that you track the audio source by name (sound_source) next to the Index (sound_source_index)

I noticed that somehow the non-cli version keeps it's selected source device even thoug the Index in Windows has changed while the sound_source value in the config_cli.toml keeps updating.

Would it be possible to add a cli-option to select the audio-source per device-name instead of the Index number to stop it from shifting if the Index in Windows is changed?

**Comment by dheijl** [comment]
I chose the device index for cli because it is easier to type, without considering the possibility of the index changing as you plug in or remove devices...
I suppose I will have to add the possibility of specifying a name (perhaps a unique substring of the name would do?).

**Comment by benkra66** [comment]
it only happened to me because i wrote a simple batch script that starts swyh-rs-cli and changes my default audio device to some unplugged SPDIF port so that the sound only gets played via my Volumio Server. 

Since it's only ever written once i guess using the full device name as it is displayed under the "sound_source" variable in the config_cli.toml as well as the program log under "name"

`16:17:00 [INFO] tb_log: Found Audio Source: index = 4, name = MeteorStereo (High Definition Audio Device)`

wouldnt be to much of a hassle.

Parsing the string and selecting a matching device via grep (or some similar function) would certainly be possible but could always result in some weird behavior with two similar named devices.

**Comment by dheijl** [comment]
> Parsing the string and selecting a matching device via grep (or some similar function) would certainly be possible but could always result in some weird behavior with two similar named devices.

That's why I wrote "a _unique_ substring". There's also the problem of two identically named cards (it does happen!) to tackle. That's why a sound source index exists in the config as well as the name..

**Comment by benkra66** [comment]
> That's why I wrote "a _unique_ substring". There's also the problem of two identically named cards (it does happen!) to tackle. That's why a sound source index exists in the config as well as the name..

sorry, i misunderstood what you ment by "unique substring", since i thought the device name windows uses would for sure be unique. 
I just tested it because i havent thought it would allow two identically named devices.. but it does.

**Comment by benkra66** [comment]
Some more testing.

Since the "given" name of a specific audio device can easily be changed in the Windows sound settings and is reflected in the config of swyh-rs a name collision could easily be circumvented.

But, to be honest, i have no idea how a change like this would affect other Operating systems.

**Comment by dheijl** [comment]
I think I will allow to append a :n to the name string (where n is the zero-based position of the duplicate card name).

**Comment by dheijl** [comment]
It all works here, if you're prepared to test I can make a pre-release.
You just specify -s some-unique-substring-of-the-name, or if they are not unique, append a :n to the substring.
The old way of specifying an index works as before.

**Comment by benkra66** [comment]
Sure, i can test it whenever youre ready

**Comment by dheijl** [comment]
You can try the [new prerelease](https://github.com/dheijl/swyh-rs/releases/tag/1.10.0-rc1).

Any comments welcome.

**Comment by benkra66** [comment]
Hello, sorry for replying so late, work got the better of me in the last few days.
I tried some different combinations, changing audio card names and devices.
As far as i can tell everything works exactly as expected and i can address all of my cards via their respective name. For the Windows side of things i couldn't find any Problems.
Big Thanks, this change spared me of some Headache when changing devices.

**Comment by dheijl** [comment]
Glad that it works. I expect to release 1.10.0 soon.

**Comment by dheijl** [comment]
As 1.10.0 is released I'll close this now.
