### ISSUE TITLE
Source Device is not muted once streaming is started which causing to hear source + Wireless speaker

### ISSUE THREAD

**Issue by YHSX88** [dheijl/swyh-rs#127]
**Usage:**
Wireless speaker: Denon Home 150
Windows 11 
Realtek Audio driver
Latest version of swyh-rs **V1.10.2**

The problem(not always reproduced) is that when I select the wireless speaker the windows sound is not auto muted and I hear the sound from the win 11 laptop and the wireless speaker 

Has someone experienced this and how to fix it ?

![image](https://github.com/dheijl/swyh-rs/assets/16823745/9baf38be-bdc4-4f07-8ee0-94c6977259f7)

**Comment by dheijl** [comment]
swyh-rs simply captures system audio, it does not control system audio.

You could use the windows audio mixer to direct the Spotify music output to a device that is not connected (like headphones) and capture that in swyh-rs.

Or you could use a virtual audio driver like VB-Audio Cable or VB-Audio HIFI Cable, configure that as the audio output device for Spotify in the audio mixer, and capture that in swyh-rs. It's what I do.

**Comment by YHSX88** [comment]
Thanks for the fast reply. just to give a heads up. I tried what you said with steam streamer device and another nahimic device and I was getting super slow play ... not delay but slow play of sounds. then I installed as you suggested VB Cable and set it as stream source and all good now. 
Thanks once again !
