### ISSUE TITLE
just a tips for windows proxy user with lagging and stuter problem on sonos

### ISSUE THREAD

**Issue by konyong** [dheijl/swyh-rs#130]
just a tips to user with lagging and stuter problem in windows,
if you use proxy, use ccproxy.

i change from proxifier to ccproxy - config it,
and my sonos never stutter or lag anymore.

**Comment by dheijl** [comment]
Can you describe your setup with ccproxy a  bit more in detail? It might be worth adding it to the readme, perhaps creating a separate Sonos section?

**Comment by konyong** [comment]
![Screenshot_2](https://github.com/dheijl/swyh-rs/assets/24316940/a93fcc6c-fdbd-482b-bb71-615ed14d813d)
here is my set-up, i enable cascading proxy mode.

**Comment by dheijl** [comment]
I updated the readme with a reference to your post, thanks!

**Comment by elliotmelcer** [comment]
@konyong could you share your swyh-rs setup aswell? Thanks!
