### ISSUE TITLE
Volume control on Windows

### ISSUE THREAD

**Issue by techquestions** [dheijl/swyh-rs#131]
Thank you for this great software.

I am using `swyh-rs` to connect to a Raspberry Pi with a Volumio running on it.
Everything works correctlly expect for the volume control - using it doensn't seem to have any effect.

Now before I will submit this is an issue, is there anything I should check on my side?

I have only used Volumio with a macOS before, where it works out of the box, including the volume control.

**Comment by techquestions** [comment]
@dheijl I'm attaching the file.
[log.txt](https://github.com/dheijl/swyh-rs/files/15274344/log.txt)

**Comment by dheijl** [comment]
From the log everything seems normal and it should work: swyh-rs is able to read the corrent volume, and it is reported by Volumio at 100 %:

```xml
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<u:VolumeResponse xmlns:u="urn:av-openhome-org:service:Volume:1">
<Value>100</Value>
</u:VolumeResponse>
</s:Body></s:Envelope>
``` 
And subsequently you try to set it several times (100%, 69%, 25% ...) and everytime Volumio acknowledges the command with success: 

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
<s:Body>
<u:SetVolume xmlns:u="urn:av-openhome-org:service:SetVolume:1">
<Value>100</Value>
</u:SetVolume>
</s:Body>
</s:Envelope>
```


```xml
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<u:SetVolumeResponse xmlns:u="urn:av-openhome-org:service:Volume:1">
</u:SetVolumeResponse>
</s:Body></s:Envelope>
```

So it could be a setting in the Volumio UPNP/DLNA setup or a Volumio limitation/bug.

**Comment by techquestions** [comment]
The problem was in Volumio's configuration. 

In the Settings, there is a "Mixer" option with the following description:

> Select the Mixer Type: None = No volume control, Software = Volume control but loss of Audio Quality, Hardware = Best of both worlds, provides ability to change volume without loss of quality

In my case there was no "Hardware" option. 
The select was set to None and that was the cause of the problem. I decided to keep it that way, because of the higher Audio Quality according to Volumio team.

**Comment by dheijl** [comment]
Thanks for the feedback! Hardware volume control needs support from the DAC, I think some  HiFiBerry DACs have it.
