### ISSUE TITLE
How to configure firewall to run swyh-rs

### ISSUE THREAD

**Issue by DrCWO** [dheijl/swyh-rs#132]
I downloaded the latest release but if I start it on Win11 I see the message below for minutes.
After this looooong time if I change something in the settings the same procedure.

![image](https://github.com/dheijl/swyh-rs/assets/65152014/9406a2df-dda5-47ef-a885-88c8c4db70b3)

Thie means not useable for me :-(

I tried to add an exception to the Windows firewall but was that for this App mo exception can be granted.

Any ideas?

**Comment by dheijl** [comment]
Sometimes windows 10 defender flags it as containing a trojan virus, but it's a false positive. That may be the reason. I don't use windows  11 myself.

**Comment by dheijl** [comment]
As there has not been any activity, I'll close this for now. You can always reopen if needed.
