### ISSUE TITLE
Distorted and interrupted sound with 24/94

### ISSUE THREAD

**Issue by DrCWO** [dheijl/swyh-rs#134]
Hello,
I try to use swyh-rs as it seems to be exactly the missing link for me. Thanks for your effort.

Playing around with it I encounter an issue I'm to able to solve by myself so support would be appreciated :-)

In my setup I use Roon as Audio Source that streams to the input virtual Hi-Fi Cable with 24/96. I connect swyh-rs to the output of Hi-Fi Cable and anyting looks good I think as RMS-Monitor shows a signal.

![image](https://github.com/dheijl/swyh-rs/assets/65152014/3ce867c5-df4b-4609-a0c2-fae1468e709b)

Next I started Firefox on a different PC and connected to `http://192.168.0.247:5901/stream/swyh.flac`
I see a progress bar and hear music but is distorted and interrupted. In one word not usable.

Next I started Foobar and tried to stream to it with the same result. 
![image](https://github.com/dheijl/swyh-rs/assets/65152014/9acab6e6-fa30-4c73-8676-9af253158ab3)

I need an idea of what goes wrong here and how to resolve it please.

Edit: 
After this experience I tried with 48kHz and this seems to work. But this is no solution for me as I need to run it with 96kHz sample rate :-(

Best DrCWO

**Comment by DrCWO** [comment]
Hmmm, crazy I runin issues with this. I have an Intel i/ so should be fast enough :-(

**Comment by dheijl** [comment]
So Roon is running on the same pc as swyh-rs?

**Comment by DrCWO** [comment]
Yes. This is my Roon Server and I grab the Roon ASIO output with VoiceMeeter Banana, send it from there to VST Host Light (ASIO), process it there, stream back to VoiceMeeter banana (ASIO). From there to Virtual Hi-Fi Cable and into swyh-rs.
All on one machine but load is below 30% at 96kHz...

**Comment by dheijl** [comment]
I don't think that cpu load is the issue, but latency is unpredictable with so many processes fighting for cpu. 
Also, unlike vb cable, hifi cable does not resample, so the sampling rates should match everywhere.

**Comment by dheijl** [comment]
As there has not been any activity, I'll close this for now. You can always reopen if needed.
