### ISSUE TITLE
Missing VCRUNTIME140.ddl

### ISSUE THREAD

**Issue by rukemn** [dheijl/swyh-rs#137]
Hey, thanks for this project.
Current issue im having when trying to install onto a new windows 10 installation:

To reproduce:
downlaod newest release, extract and execute Setup-swyh-rs - no apparent problems.
download newsest release, extract and execute swyh-rs-release. 

The following error appears:
![image](https://github.com/dheijl/swyh-rs/assets/33164303/c8fc594a-b79b-471e-a8a9-c001b2afd489)

Thanks in advance, im happy to provide more details if needed :)

**Comment by dheijl** [comment]
Rust binaries need the visual studio 2015 runtime distributable installed, you can get it from: 

https://aka.ms/vs/16/release/vc_redist.x64.exe.

It is normally already installed because so much software relies on it, but on a fresh installation it is probably not yet installed.

**Comment by rukemn** [comment]
Thanks for the quick reply. That fixed the issue. 
The dll download can also be found here (https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) 

Maybe for a future release, bundling it with the setup would be benefitial.

**Comment by dheijl** [comment]
I'm considering it.
