### ISSUE TITLE
LAN Radio

### ISSUE THREAD

**Issue by MX10-AC2N** [dheijl/swyh-rs#14]
Hi Dheijl,
Would it be possible to add an option to broadcast the sound in a sort of web-radio easily accessible from an internet browser or vlc ?
Actually if I try access http:// "my ip" /stream/swyh.wav with "Opera web browser" or "VLC" the streaming is impossible...
That would be a really interesting option.
Thank you.

**Comment by dheijl** [comment]
I'm sorry but VLC and Opera (and Firefox and Chrome) do not support "naked" audio/l16 LPCM streams as used in DLNA.

**Comment by dheijl** [comment]
But I have good news for you: Foobar2000 will happily play swyh-rs streams, I'm currently listening to http://192.168.0.135:5901/stream/swyh.wav (use "add location" from the foobar2000 file menu, choose your output, and press play. Foobar2000 is free and is an excellent media player that uses very little resources.

**Comment by MX10-AC2N** [comment]
Thanks, I will try Foobar2000 mobile for Win10 Mobile..

**Comment by MX10-AC2N** [comment]
And unfortunately it doesn't work with foobar2000 mobile, I can ask to read http://'My IP':5901/stream/swyh.wav but the playback does not start .. Well that's for sure windows 10 phone is a real good shit but I only have that as a phone ...

**Comment by MX10-AC2N** [comment]
It worked once, but after several attempts to restart the playback of the stream, it doesn't work .. I will look for other applications to read the stream <http: // 'my ip' / stream / swyh.wav> (W10 Phone pisses me off more and more ...)

**Comment by dheijl** [comment]
You could install foobar2000 on Windows 10, configure the upnp media renderer output (configuration file, see image), let it stream from swyh-rs (add location), and use VLC on Windows 10 Mobile as an dlna renderer to stream from the foobar2000 dlna server. It could work.

![Knipsel](https://user-images.githubusercontent.com/2384545/97806404-c7864800-1c5b-11eb-8328-de9ade693ee2.PNG)

**Comment by MX10-AC2N** [comment]
Foobar2000 mobile can read the stream..! Just put the reading in loop to avoid losing the flow...

**Comment by dheijl** [comment]
Good to hear! But how do you "put the reading in a loop" ?

**Comment by MX10-AC2N** [comment]
When Fobar2000 mobile read swyh.wav there is an option for read in loop.. Always the same playlist with one file http://'my ip':(çà&/stream/swyh.wav

**Comment by dheijl** [comment]
OK now I see, thanks for the explanation!
