### ISSUE TITLE
V0.9.7

### ISSUE THREAD

**Issue by MX10-AC2N** [dheijl/swyh-rs#16]
Hi dheijl,
I install and try your new release.. And when I changed LOG level or Input Source, I can't see a Restart Button.

Another thing, I do not see the usefulness of the SSDP discovery at regular and adjustable interval, I think that in a classic use, it would be more useful to just put a button to restart the SSDP discovery. When I use swyh-rs on a renderer that is already active and that I turn on my tv for example, it is easier for me to manually search for my tv rather than wait for automatic discovery.. Anyway it works well, but if I start swyh-rs, ssdp discovery find my Harmann I start th stream, then after a moment I start my TV, the GUI give me :
![Capture d’écran (8)](https://user-images.githubusercontent.com/62643837/98654001-05f7c300-233e-11eb-8081-5a32d73ad04e.png)
Sorry but always GUI bug.. But nothung serious..

Have a nice day..

**Comment by MX10-AC2N** [comment]
Ah yes also a little thing that I wanted to tell you, it is to make an automatic return to line in the info window so as not to have to do a side translation to see all the info..   ;-)

**Comment by dheijl** [comment]
Yes, resizing is not handled properly because there is currently no way that I can see in fltk-rs to handle resizing. The restart button is to the right of the window and thus invisible in your screenshot. I will have to think about the resizing problem, and the gui layout in general for that matter.

**Comment by MX10-AC2N** [comment]
In fullscreen mode I haven't restart button..
![Capture d’écran (9)](https://user-images.githubusercontent.com/62643837/98662210-bf0ecb00-2347-11eb-8aec-a9e04d9902a9.png)

**Comment by MX10-AC2N** [comment]
And at the minimal size.. ;-)

![Capture d’écran (10)](https://user-images.githubusercontent.com/62643837/98663682-aef7eb00-2349-11eb-8a76-96d37d1f3b75.png)

**Comment by dheijl** [comment]
It has "fallen off" the window and is not visible. Has to do with screen resolution and a windows font size > 100 %...

**Comment by MX10-AC2N** [comment]
My screen resolution is 1280X800 at maximum .. I did not quite understand what to do as a modification in the display settings ?

**Comment by dheijl** [comment]
The restart button is now replaced with a pop-up.
You do not have to do anything, the problem is in the fltk-rs library, it does not expose the native fltk screen_scale() and screen_dpi() functions, and that makes GUI layout difficult for different screen sizes and screen resolutions (dpi).

**Comment by dheijl** [comment]
Resizing is a *little* bit better now, but I don't see how to get it right with the current FLTK version (widgets get resized vertically too, no anchors, no layouts...).

**Comment by MX10-AC2N** [comment]
Hi, I try V1 but at minimal size I have :
![Capture d’écran (11)](https://user-images.githubusercontent.com/62643837/98912392-569a2800-24c6-11eb-9202-01ab34c19abb.png)
and at fullscreen
![Capture d’écran (12)](https://user-images.githubusercontent.com/62643837/98912419-63b71700-24c6-11eb-942e-786ed34fb4f4.png)
It's not really better for me, sorry.. FLTK seems quite restrictive indeed.

**Comment by dheijl** [comment]
Thanks to @MoAlyousef resizing is now much better (V1.0.1), but you can still lose the horizontal scrollbar at the bottom ...
