### ISSUE TITLE
Feature requested

### ISSUE THREAD

**Issue by resom78** [dheijl/swyh-rs#19]
As this app works so well, I would like to know if it would be possible to add a feature to reconnect automaticaly to the last renderer choosen?
With this feature I couldlaunch the app when windows starts and use it like a sound card!

**Comment by dheijl** [comment]
It'sprobably a good feature, I'll give it a thought, thanks!

**Comment by dheijl** [comment]
This should now work.

**Comment by resom78** [comment]
yes it works great!! thanks again
