### ISSUE TITLE
Sound delay

### ISSUE THREAD

**Issue by resom78** [dheijl/swyh-rs#21]
Hi again,
I don't know if it is really an issue, but I would like to know if it is possible to reduce the delay between the audio played on computer and the sound played bythe renderer (for me a chromecast)?
I have 1.5s which is not bad I think, compared to other app like LAB, Chromecaster GUI... but if it could be improved it would be really great!
Thanks

**Comment by dheijl** [comment]
I understand but unfortunately there's nothing I can do about that, swyh-rs does not introduce any delay except for the buffering in Windows, in swyh-rs, in the http stream and in the end device. It all adds up I'm afraid.
