### ISSUE TITLE
Volume difference

### ISSUE THREAD

**Issue by MX10-AC2N** [dheijl/swyh-rs#23]
Hi dheijl, little feedback .. 
As you know I use swyh-rs especially with Deezer, today I am testing the sending of sound with Youtube launched on Microsoft Edge, and I have, despite having the volume Max on youtube, a very low volume in the swyh-rs stream .. I also tried with Molotov (a French TV application) same result despite the max volume in the application the stream remains at very low level .. .
Is there a way to choose the sound level of what we send in the stream or to normalize the output stream to a level (0dB) that we could adjust?
I don't understand why I have such a low volume with Edge or Molotov while with Deezer it works well ...

**Comment by dheijl** [comment]
Hi @MX10-AC2N ,

Have you checked the volume of the browser in the Windows Volume Mixer?

**Comment by MX10-AC2N** [comment]
I don't know what happened again but hey after restarting the whole system, it is much better, I still have a difference in volume between the applications but quite slight ... Sorry a little noise for Not much...

**Comment by dheijl** [comment]
No problem!

**Comment by MX10-AC2N** [comment]
Thanks again for everything you do ..
