### ISSUE TITLE
Autoreconnect doesn't work anymore

### ISSUE THREAD

**Issue by resom78** [dheijl/swyh-rs#25]
Hi, 

I use your app since the beginning and when you added the autoreconnect feature it worked.
But until version 1.1.1 it doesn't work, when I check the box, close the app and open it again, the box is unchecked...

**Comment by dheijl** [comment]
It works here with the latest version (1.2.0).

It's possible that the addition of the "disable chunked transfer encoding" setting somehow corrupted your config file.
You can find it here: `C:\Users\{your_user_name}\swyh-rs\config.ini` 

Deleting this file should fix it (but you will lose your current settings, like the audio source if not default).

**Comment by dheijl** [comment]
Should be fixed in 1.2.1. Sorry about that...

**Comment by resom78** [comment]
I will try your tip with the config file

**Comment by dheijl** [comment]
Not needed with 1.2.1

**Comment by resom78** [comment]
Ok it works! Thanks a lot
