### ISSUE TITLE
Hide GUI

### ISSUE THREAD

**Issue by Silun** [dheijl/swyh-rs#26]
Thank you for making swyh-rs!
I use it to send application audio to Chromecast devices like so:

`App -> VB-Audio HiFi Cable -> swyh-rs -> BubbleUPNP -> Chromecast`

In this scenario, ideally the chain is "always on" and I just fire up any given application, start the audio, and it should start playing on my speakers. That kind of works already, however I can find no way to autostart swyh-rs in the background. Is there a way to send it to tray, or hide the GUI altogether, or run it in daemon/system service mode? Basically, what I am asking is to be able to use swyh-rs without having to have the program window running. Maybe a `--tray` switch could be implemented that will run it GUI-less with a simple tray icon to close it, or something along those lines.

**Comment by dheijl** [comment]
Unfortunaltely the cross-platform GUI library (FLTK) that I use does not support tray icons (as far as I know).
But I can see your point. I could add add an option to start up the app minimized, where this option would  only available when autoreconnect is set to  true.
Would that be enough? This way you can close swyh-rs from the taskbar and you will never see the GUI if you don't want to. You would only have to use the GUI once to select the "default" renderer that from then on will be used to automatically reconnect on startup.

**Comment by Silun** [comment]
Are you talking about minimized as in the same thing that happens when I make a shortcut to swyh-rs and set that shortcut to start minimized? That would not be what I am looking for, as the window would still get in the way of Alt-Tabbing and Win-Tabbing.

Then again, the tray icon is just one of many possible solutions. Off the top of my head, a `--toggle` switch might work. That could run a head/GUI-less version of it, without any window, tray icon, etc. just an "invisible" process in the background. Running it again with the `--toggle` could shut it down again. Not sure if that is easy to implement in rust, though. For me personally it would suffice to have a way of running swyh-rs without any GUI/window whatsoever even if killing it in task manager was the only way to stop it. The configuration is very set-and-forget, so I would not need to see or use the GUI very often anyway.

**Comment by Silun** [comment]
I looked into it a bit and found a solution that works for me. I use this Python script which is located in the same folder as `swyh-rs.exe`:

```python
import subprocess

def startProgram(target):
    SW_HIDE = 0
    info = subprocess.STARTUPINFO()
    info.dwFlags = subprocess.STARTF_USESHOWWINDOW
    info.wShowWindow = SW_HIDE
    subprocess.Popen(target, startupinfo=info)

program = r'swyh-rs.exe'

startProgram(program)
```
It will run `swyh-rs.exe` while _suppressing the window completely_. I put a shortcut to it in `shell:startup` so it will run automatically on user logon. This does what I wanted to accomplish, it _just works_ now, without any window showing up. 
Thank you!

**Comment by dheijl** [comment]
That is a very neat solution. I will add add it to the readme or start a wiki and put it there, so that others could use this too. Thanks!

**Comment by instinctualjealousy** [comment]
On Windows, I wish to achieve a headless/No GUI usage of swyh-rs. Does that Python solution increase swyh-rs' CPU usage for you, @Silun? I usually turn things into services with NSSM, but swyh-rs' CPU usage shoots up to 7% even on idle when configured this way. A simpler method less prone to user error (I imagine), NirCmd's `exec hide`, causes the exact same CPU usage spike. You wouldn't think the software would be aware that the UI window isn't being created, but it probably is, and isn't happy with it.

Native-ran (usually hangs around <0.01% when in use):
![image](https://github.com/dheijl/swyh-rs/assets/13276804/2f6828e4-e72e-4cc0-8d39-cd8bcd740b73)

Force-hidden:
![image](https://github.com/dheijl/swyh-rs/assets/13276804/11b3593b-eff9-41e5-a007-57d33e9289a1)

**Comment by Silun** [comment]
How many cores or threads does the processor on your system have? Is it 16 by any chance? I have noticed this issue as well and changed the way I handle it for this reason.

I believe that when swyh-rs is run with the GUI completely hidden, as in, it never shows up at all, a single thread will be at 100% utilization. So 6.64% from the screenshot would roughly match 1 out of 16 threads. I now use [Trayifier](https://github.com/Silun/Trayifier) to run swyh-rs and switch on the GUI briefly at some point (or starting it with the GUI showing, and then hide it). The moment the GUI shows up, the high utilization fades to regular levels (as far as I remember). I always assumed it was a bug in the GUI framework you were using, so it would just get fixed eventually - I didn't bother to mention it.

**Comment by instinctualjealousy** [comment]
6T/12C actually, Intel Xeon W-2135. I'm trying to remember if my CPU usage was higher on my 4C/8T E5-1620. I'd actually rather not have it in the tray if possible- or I can eat the CPU usage. It's just kind of a big loss compared to the near-zero usage, though.

This might be a good argument for a built-in hidden mode (I agree that I don't really need the ability to close it, either) if it can get around the UI bug somehow (by flashing the UI at the start or doing something else internally).

**Comment by Silun** [comment]
Well, it was either gonna be 16 or 12, the math was around that area :)

I mean, just try and add a delay to the hiding.

1. Run SWYH-RS
2. Wait 3 seconds
3. Hide its windows for good

I'm not home right now, but you could use the code that Trayifier uses to make that script. Something like this:


```python
from win32gui import EnumWindows, ShowWindow, SetForegroundWindow
from win32process import GetWindowThreadProcessId
from time import sleep

def find_window_for_pid(pid):
    """Find all windows associated with the passed PID by iterating through all windows and comparing the associated PIDs."""
    result = []
    def callback(hwnd, _):
        nonlocal result
        ctid, cpid = GetWindowThreadProcessId(hwnd)
        if cpid == pid:
            result.append(hwnd)
    EnumWindows(callback, None)
    return result


def change_visibility(hwndlist, bool):
    """Change the window visibility of the passed list of HWND window handles and push into foreground.
    The function SetForegroundWindow() is buggy in Windows, it can lead to occasional crashes - there are
    added shell commands which are intended to alleviate this issue."""
    for hwnd in hwndlist:
        ShowWindow(hwnd, bool)
        if bool:
            # Send keys to work around an issue in the Windows API.
            try:
                shell.SendKeys('%')
                SetForegroundWindow(hwnd)
                shell.SendKeys('%')
            except Exception as e:
                print("Exception occured on setting window focus. This is a bug in the Windows API.")
                print(e)
    return bool

swyh_handle = subprocess.Popen(path_to_swyh)
sleep(3)
swyh_windows = find_window_for_pid(swyh_handle.pid)
change_visibility(swyh_windows, False)

```

I put that thing together in this comment box right here though, so check it for mistakes.

**Comment by dheijl** [comment]
Did you consider using swyh-rs-cli instead, available since some time? No gui, all commandline arguments.

**Comment by instinctualjealousy** [comment]
I need to learn to RTFRN, That's perfect. I actually had an out-of-date version due to the fact I forgot the scoop extras manifest was out of date. I'm building a new manifest for my bucket.

**Comment by instinctualjealousy** [comment]
I am confused though- it seems to insist on hooking up to a renderer, and terminating when it can't find one. This is not the behavior of the GUI app. I'm looking over -h and the project description and I'm stumped. My use-case doesn't involve using it to push to a renderer. The GUI app has worked for my use case (simply hosting the swyh.wav on port 5901 and having foobar push it over a UPnP server via a network location).

**Comment by dheijl** [comment]
I didn't think of that use case.
Can you create a new issue for that? Shouldn't be too hard to add it to the cli with a new command-line option (don't  start streaming,  just serve on port 5901 ).

**Comment by instinctualjealousy** [comment]
@Silun, thank you for your assistance earlier, even if I ended up not needing it.

**Comment by dheijl** [comment]
@Silun: I think that the latest version of swyh-rs-cli (see #111) should make things a lot easier.

**Comment by Silun** [comment]
It certainly sounds that way! Thank you.

**Comment by phil2sat** [comment]
Here is some code which does what i need, its also possible to show and minimize again trough the trayicon
cpu usage of the process while minimized is for me at around 0.1-0.2% while streaming to my speaker
it needs also an icon.png in the same folder, can extract .ico with 7zip from .exe and save as png


name it "swyh-rs.pyw" and copy into swyh-rs folder

`import subprocess
import time
import win32gui
import win32process
import win32con
import pystray
from PIL import Image
import sys

def start_program(target):
    """Startet das Programm und gibt das Prozessobjekt zurück."""
    process = subprocess.Popen(target)
    return process

def find_window_for_pid(pid):
    """Findet alle Fenster, die mit der übergebenen PID verknüpft sind."""
    result = []
    def callback(hwnd, _):
        nonlocal result
        ctid, cpid = win32process.GetWindowThreadProcessId(hwnd)
        if cpid == pid:
            result.append(hwnd)
    win32gui.EnumWindows(callback, None)
    return result

def minimize_to_tray(process):
    """Minimiert das Programm in den System Tray."""
    hwnds = find_window_for_pid(process.pid)
    for hwnd in hwnds:
        win32gui.ShowWindow(hwnd, win32con.SW_HIDE)

def show_program(process):
    """Zeigt das Programmfenster an."""
    hwnds = find_window_for_pid(process.pid)
    for hwnd in hwnds:
        win32gui.ShowWindow(hwnd, win32con.SW_SHOW)
        win32gui.SetForegroundWindow(hwnd)

def create_tray_icon(process):
    """Erstellt ein System Tray-Icon mit Menü."""
    image = Image.open("icon.png")  # Pfad zum Icon
    menu = pystray.Menu(
        pystray.MenuItem("Show", lambda: show_program(process)),
        pystray.MenuItem("Minimize", lambda: minimize_to_tray(process)),  # Minimieren-Button
        pystray.MenuItem("Exit", lambda: exit_program(icon, process))
    )
    icon = pystray.Icon("swyh-rs", image, "swyh-rs", menu)
    icon.run()
    return icon

def exit_program(icon, process):
    """Beendet das Programm und das Tray-Icon."""
    process.terminate()
    process.wait()
    icon.stop()
    sys.exit(0)  # Beendet das Python-Skript vollständig

if __name__ == "__main__":
    program = r'swyh-rs.exe'
    process = start_program(program)
    time.sleep(2)  # Kurze Verzögerung, um das Fenster anzuzeigen

    # Minimieren in den Tray
    minimize_to_tray(process)

    # Erstelle das Tray-Icon
    icon = create_tray_icon(process)`

**Comment by dheijl** [comment]
Thanks for sharing this! 
I will add it to the wiki and reference it in the readme.

**Comment by dheijl** [comment]
Should I use PyInstaller and bundle your program as an exe with the Windows installer?
