### ISSUE TITLE
Sonos test

### ISSUE THREAD

**Issue by Cunkers** [dheijl/swyh-rs#30]
Tried using program with sonos, get "the song is not encoded correctly" 
so assuming it wont work with sonos speakers.

**Comment by dheijl** [comment]
If you get this far it may be something that is easy to fix. But as I don't have Sonos speakers I would need your help to find out what's going wrong, provided you are interested of course.
It might be something as trivial as the ".wav" extension that makes Sonos expect a real WAV file format instead of the "naked" WAV data (LPCM 16 bit) stream. This might be easy to fix (other extension, no extension, ...) or not fixable at all.

**Comment by dheijl** [comment]
After having a look at the [Sonos developer documentation](https://developer.sonos.com/build/content-service-add-features/supported-audio-formats/) I see that Sonos does not support the type of streaming used by swyh-rs (audio/l16). Only audio/wma and audio/x-ms-wma (real WMA files) are supported for raw PCM data. So it is not trivial at all.

**Comment by Cunkers** [comment]
Ah I see, well any help you need (access to my sonos speakers) im more than glad to help

**Comment by dheijl** [comment]
I'll have a go at implementing WAV file format support, see also [issue 31](https://github.com/dheijl/swyh-rs/issues/31) and let you know if something is ready to test.

**Comment by dheijl** [comment]
There's a new [beta ](https://github.com/dheijl/swyh-rs/releases/tag/1.3.5-beta)in releases with WMA file format support.

**Comment by dheijl** [comment]
There's a new [beta ](https://github.com/dheijl/swyh-rs/releases/tag/1.3.5-beta)build with WAV support now, but I don't know  if it will work for you...

**Comment by dheijl** [comment]
Did you give the WAV support a try? Or have you lost interest?

**Comment by Cunkers** [comment]
Hello, i'm ever so sorry for not getting back to you. I had alot going on and wasn't able to even have the time to sit down.

Just tried the 1.3.5 build with WAV support which resulted in the same error "swyh.wav" - this song is not encoded correctly

but upon trying the 1.3.10 build... success! it works. really appreciate you actually making it possible and getting back to me.

**Comment by dheijl** [comment]
This really good news, thanks for trying!
