### ISSUE TITLE
Audio streaming on Linux not working | Connection immediately terminated

### ISSUE THREAD

**Issue by FinalSh4re** [dheijl/swyh-rs#31]
Hi,

first of all thanks for your hard work. I can't get the audio casting on Linux (Manjaro 20.2.1) to work though.
The renderer is found on the network, but the connection is terminated immediately. No audio is played either.

I attach the log, maybe you can see where this is going wrong. If you need further information, let me know.

Cheers!

Log file:
[log.txt](https://github.com/dheijl/swyh-rs/files/5981651/log.txt)

**Comment by dheijl** [comment]
Everything seems to work as expected for an AVTransport DLNA player, except for the streaming of the music. 
It's possible that it does not accept the "naked" PCM audio stream (audio/l16), perhaps it needs a WAV header, maybe the same problem as with Sonos speakers.
I could make a test release that sends the stream in WAV format if you're interested.

**Comment by FinalSh4re** [comment]
Sure, if you think that will do the trick I would appreciate it.

**Comment by dheijl** [comment]
OK I'll look into the WAV format and will try to get that working here. If it works I'll make a beta release. Thanks!

**Comment by dheijl** [comment]
There's a new [beta ](https://github.com/dheijl/swyh-rs/releases/tag/1.3.5-beta)in releases with WMA file format support.

**Comment by FinalSh4re** [comment]
Thank you, I made a test run and checked a few different setting combinations. The connection is now stable and no longer drops, however i hear mostly static noise through the speakers.

**Comment by dheijl** [comment]
Yes, it's not OK yet. But I think I know where the static noise comes from.

**Comment by dheijl** [comment]
What combination of settings got you the stable connection?

**Comment by FinalSh4re** [comment]
The connection was stable as long as the new 'Use WMA/WAV Format'-Checkbox was toggled.

**Comment by dheijl** [comment]
OK thanks!

**Comment by dheijl** [comment]
In theory the WAV format is correct now (in the [1.3.5-beta](https://github.com/dheijl/swyh-rs/releases/tag/1.3.5-beta)) for "infinite" streaming, depending on how the renderer opens the stream.

**Comment by FinalSh4re** [comment]
It works like a charm. Thanks a lot! 

Just fyi I seem to get the best result with the "use wma/wav format" + "disable chunked transfer encoding" boxes toggled. Without the latter checked the audio seems a bit unstable at times (noise and stuttering), nothing major but still noticeable. I tested it against the same source audio streamed from my iPhone and both streams sound the same to me. Hope this helps.

Cheers!

**Comment by dheijl** [comment]
Thanks for the feedback! Glad that it works for you, it does not work for me with a Volumio streamer because of the libsndfile problem, so I can not test it myself.

**Comment by dheijl** [comment]
As an aside: on Linux if you run swyh-rs as root (sudo) it will renice itself to a higher priority in an attempt  to prevent stuttering. Or you can renice it yourself once it is running. On Windows it will always raise priority a bit.

**Comment by FinalSh4re** [comment]
Thanks for letting me know, you also mentioned this in the documentation. I'll try giving the process a higher priority should I encounter any performance issues. So far turning off the chunked transfer encoding has been enough to get stable output. However, I haven't really tested streaming while running any resource intensive processes in parallel so this option might come in handy in the future.
