### ISSUE TITLE
Automatic download of latest release

### ISSUE THREAD

**Issue by ksz16** [dheijl/swyh-rs#34]
I can get tag_name correctly from https://api.github.com/repos/dheijl/swyh-rs/releases/latest 
But link https://github.com/dheijl/swyh-rs/releases/latest/download/swyh-rs-1.3.8.zip doesn't work.
It would be great if this feature worked. This makes it possible to use in scripts.

https://docs.github.com/en/github/administering-a-repository/linking-to-releases#linking-to-the-latest-release

**Comment by dheijl** [comment]
OK I put the binaries in assets now so that the links will now work.

Thanks for pointing this out to me!

**Comment by ksz16** [comment]
Thank you for your quick response.
And for all your work - swyh-rs is a great piece of software.

**Comment by ksz16** [comment]
Maybe it will be useful for someone.
Tested on Windows 7 with Cygwin installed and curl and grep added to PATH.
```
FOR /F "tokens=*" %%G IN ('curl -s https://api.github.com/repos/dheijl/swyh-rs/releases/latest ^| grep -oP '^"tag_name^": ^"\K^(.*^)^(^?^=^"^)'') DO set LATEST=%%G
curl -L https://github.com/dheijl/swyh-rs/releases/latest/download/swyh-rs-%LATEST%.zip -o %TEMP%\swyh-rs-%LATEST%.zip
```

**Comment by dheijl** [comment]
Great! I'll add this to the wiki.
