### ISSUE TITLE
Error capturing f32 audio stream on Windows

### ISSUE THREAD

**Issue by JWolvers** [dheijl/swyh-rs#36]
Hi,

I would like to use your software to stream music to a Volumio server, but when I do so I have no sound. The log shows an error about capturing the audio, this happens on two machines I tested it on. I also tested with the VBAudio HiFi Cable but I get the same error. I hope you can fix this!

[log.txt](https://github.com/dheijl/swyh-rs/files/6140233/log.txt)

**Comment by dheijl** [comment]
Hi,

The most likely cause is that the application playing the audio has opened the WasApi device in exclusive mode. Foobar2000 is an example of such an application. 
There are ways around this using the Windows audio mixer. For instance with Foobar2000 you choose the default audio output and in the sound mixer you direct the Foobar2000 output to VB audio.
(But with Foobar2000 you don't need swyh-rs as it suports upnp/dlna directly.)

What application are you using to play audio?

**Comment by JWolvers** [comment]
Hi,

I am using Firefox on Windows 10, but the issue is most likely caused by Kaspersky.
I will contact our IT provider about creating an exception for swyh-rs and see if that solves the problem and report back.

Thanks for your help!

**Comment by dheijl** [comment]
I have no problem with Firefox and VB-Audio Hifi Cable, so Kaspersky might indeed be the culprit:

![Knipsel](https://user-images.githubusercontent.com/2384545/111291448-7e9dc180-8647-11eb-802a-e8ef560cab4e.PNG)

**Comment by JWolvers** [comment]
It was indeed caused by kaspersky.
