### ISSUE TITLE
Sonos Play:1 doesn't play

### ISSUE THREAD

**Issue by runxel** [dheijl/swyh-rs#38]
Thanks for your work, @dheijl!

However I have trouble to get to work with a Sonos PLay:1.
Looking in the Sonos S2 app this notification will always pop up when trying to play something.
"Use WMA/WAV" is checked.

![grafik](https://user-images.githubusercontent.com/2277182/113278806-a6955200-92e2-11eb-8047-bf7b1bd300a9.png)

**Comment by dheijl** [comment]
Can it be a firewall problem? When swyh-rs is running you should be able to point a browser at http://192.168.178.128:5901/swyh.wav.

**Comment by runxel** [comment]
If I go to that address in Firefox nothing happens. Just a blank screen. (But also no "connection could not be established" or similar)

When in swyh-rs I click on the button for the Sonos I want to play. The message in the bottom pane will say:
```
AV Start playing on Sonos Play:1 Media Renderer host=192.168.178.29 port=1400 from 192.168.178.128 using AvTransport Play
```
Going to `http://192.168.178.29:1400/swyh.wav` an `Error 404 Not Found` will appear.

---

In other news I just found that Spotify sees the Sonos, and I can directly stream my music this way.

**Comment by dheijl** [comment]
Thanks for testing again.
So something (firewall or anti-virus) is blocking HTTP traffic to port 5901 on your PC (ip 192.168.178.128:5901), or another application is already using that port for something else (for instance VNC on Linux also uses port 5901).
This is also what your Sonos app reports: _Verbindung mit 192.168.178.128:5901 nicht möglich_, so the Sonos HTTP request for streaming never reaches swyh-rs.

IP 192.168.178.29 is your Sonos player and 1400 is its control port for DLNA commands (in SOAP request format).  

Also, swyh-rs is not meant to replace Spotify/Spotify Connect or Airplay or other applications that can play directly to renderers.
It is only useful as a last resource when you are playing music on a PC from a source that does not support casting to your player but your player does support DLNA/Openhome.

**Comment by runxel** [comment]
Thank _you_ for patience.

Very strange. There is no antivirus (except default Win Defender or what its called now) and the firewall is open.

But since Spotify can connect to the Sonos it seems I'm not in a big need of a solution right now....
So I will close this issue for now. Thanks again!
