### ISSUE TITLE
32bit release?

### ISSUE THREAD

**Issue by mesb1** [dheijl/swyh-rs#41]
Hi.

Is it posible to add x86 release version?

I tried replace swyh to swyh-rs, but the atom device is using licensed 32bit windows that i would like to keep.

**Comment by dheijl** [comment]
I'm sorry but I don't have a 32 bit system to test with. In theory I could try cross compiling but even if I succeeded to compile for 32 bit I would be unable to give any support if it doesn't work.

**Comment by dheijl** [comment]
I added a 32 bit Windows binary build (`target = i686-pc-windows-msvc`) to the [1.3.17 pre-release](https://github.com/dheijl/swyh-rs/releases/tag/1.3.17) in assets.
It runs on my 64 bit Windows, let me know if you run into any issues.

**Comment by mesb1** [comment]
Hm.
Well, now it is started, i am able to choose my dlna renderer - it even switched to playing - but no sound produced.
Will try to look into more closelyat weekend.

`
Configuration { server_port: 5901, auto_resume: false, sound_source: "Динамики (Realtek High Definition Audio)", log_level: Info, ssdp_interval_mins: 1.0, auto_reconnect: false, disable_chunked: false, use_wave_format: false, monitor_rms: false, last_renderer: "LG TV [TV][LG]42LN655V-ZD", config_dir: "C:\\Users\\Anton\\.swyh-rs" }
Setup audio sources
Now running at ABOVE_NORMAL_PRIORITY_CLASS
Capturing audio from: Динамики (Realtek High Definition Audio)
Default audio SupportedStreamConfig { channels: 2, sample_rate: SampleRate(48000), buffer_size: Unknown, sample_format: F32 }
Starting SSDP discovery
The streaming server is listening on http://192.168.1.99:5901/stream/swyh.wav
Sample rate: 48000, sample format: audio/l16 (PCM)
AV Stop playing on [TV][LG]42LN655V-ZD host=192.168.1.11 port=1315
AV Start playing on [TV][LG]42LN655V-ZD host=192.168.1.11 port=1315 from 192.168.1.99 using AvTransport Play
Received request /stream/swyh.wav from 192.168.1.11:45102
Streaming audio/l16 (LPCM), input sample format F32, channels=2, rate=48000, disable chunked=false to 192.168.1.11:45102

`

**Comment by mesb1** [comment]
Enabled rms tick - it doesn't show levels. It looks like it doesn't capture audio for some reason.

**Comment by dheijl** [comment]
From the log you enclosed I can see that no audio is being captured.
Capture is using WasAPI, what is your Windows version, what application is playing music, and to what device is it playing according to the Windows Audio Mixer?

**Comment by mesb1** [comment]
This is windows 7 starter edition updated to sp1.
All available security updates installed.

It was Firefox esr with YouTube video, but I also tried vlc.

Not sure how can I check it with windows audio mixer, please point me here.

**Comment by dheijl** [comment]
Windows 7 volume mixer: https://www.howtogeek.com/howto/5228/simple-tips-windows-7-volume-mixer-enables-quick-access-to-sound-settings/

**Comment by mesb1** [comment]
Well, I have it there.
I also decide to change drivers to realtek, but that doesn't help. It might be there is something wrong with wasapi for my system and it's drivers?

**Comment by dheijl** [comment]
You could try vb audio cable or vb audio hifi cable, they are known to work with WasAPI capture. You can use the volume mixer to only use vb audio for the app that you want to stream to the LG T V, leaving other sound on the default audio output. But I can not test on Windows 7 myself, I only have W10 and Linux.

**Comment by dheijl** [comment]
I'll close this now.
