### ISSUE TITLE
ssdp error with v1.3.18

### ISSUE THREAD

**Issue by MX10-AC2N** [dheijl/swyh-rs#43]
Hi dheijl,
this morning i try v1.3.18 but impossible to see my amp, here is the log 
https://paste.yunohost.org/wolijafeti.php

**Comment by dheijl** [comment]
You are right! I forgot to update the configuration value, sorry about that...
You can fix it now by selecting the network in the new network dropdown and restarting swyh-rs, or you can wait for 1.3.19.

**Comment by dheijl** [comment]
should be fixed with 1.3.19.

**Comment by MX10-AC2N** [comment]
Fixed with 1.3.19
Thank again..
