### ISSUE TITLE
Windows x64 to Sonos: Unable to connect

### ISSUE THREAD

**Issue by JakobTischler** [dheijl/swyh-rs#48]
Hi,

I'm on Windows 10 x64 and am trying to stream to different Sonos devices. SWYH finds and lists all of them correctly, I can activate each one (except obviously ones that are defined as stereo speakers, which makes sense), the log states it's streaming (`http://192.168.XX.XX:5901/stream/swyh.wav`), and in the Sonos app I can see that the speaker is playing the stream. There's no sound though. After a bit, I get an error message inside the Sonos app: `Unable to play "swyh.wav" - unable to connect to http://192.168.XX.XX:5901`.

"Add WAV Hdr" is turned on as per the readme. 

Any advice? Thanks in advance.
-- Jakob

**Comment by dheijl** [comment]
Hi,

If you don't get the message "Received request http://192.168.xxx.xxx/swyh.wav from 192.168.xxxx.xxx"  in the textbox then it looks like the Windows firewall or an anti-virus (like Kaspersky) is blocking incoming HTTP access to the streaming server, and this is also what the Sonos app suggests.

If you do get that message perhaps a debug log could give some more information.

**Comment by dheijl** [comment]
Everything seems OK but the streaming server does not get any streaming requests.
Can you point a browser from another device (pc or smartphone) at the streaming url (the url at swyh.wav:5901) ? If the server is reachable the request should appear in the textbox in swyh-rs, if not I hope you get an error from the browser with some information.
When the swyh-rs streaming server is running you should also see it in netstat or other tcp tools in Windows.

**Comment by JakobTischler** [comment]
Well, I'm (somewhat) happy to report that it's a user error :)

Your tip with trying to access the swyh server from a different device solved it. I keep my PC network defined as "public", for safety reasons, and I forgot about that. So nothing can access my PC unless I specifically allow it. Once done so for swyh-rs, I could access it and stream to the Sonos speakers successfully.

Thank you for your help, and for the program itself, of course.

**Comment by dheijl** [comment]
Glad that it now works for you!
