### ISSUE TITLE
v1.13.20 swyh-rs.zip has trojan virus

### ISSUE THREAD

**Issue by boringuy** [dheijl/swyh-rs#49]
On Windows, when trying to unzip, Windows Defender detected:

Detected: Trojan:Script/Oneeva.A!ml
Status: Removed
A thread or app was removed from this device.

Is this real or false alarm?
Triedthe v1.13.19 zip and it was ok.

**Comment by dheijl** [comment]
Looks like a false positive on downloading the zip file. I replaced the zip file with a newly compiled development version (no real changes) and I no longer get the error when downloading. Never got a virus warning on the zip files on my pc and an offline defender scan found nothing.

**Comment by dheijl** [comment]
Do you have trouble downloading the 1.3.21 zip?

**Comment by boringuy** [comment]
Thank you both 1.3.19 and 1.3.21 has no problem.

**Comment by boringuy** [comment]
Actually, I redownload 1.3.20 again and Windows Defender did not complain this time. odd. Unfortunately, Windows defender immediately removed the file, so I cannot do a checksum to compare if the file was somehow different. 

Sorry for the false alarm.

**Comment by dheijl** [comment]
Thanks for reporting this. I suppose I can close this now.
