### ISSUE TITLE
Incompatibility with Moode Audio Player 

### ISSUE THREAD

**Issue by RenEH01** [dheijl/swyh-rs#51]
Hello, thank you for this awesome software! Unfortunately, it doesn’t work with Moode audio player which is a fork of Volumio. Any idea why? I’m using the current release of Moode, 7.6.1

**Comment by dheijl** [comment]
If you could enable the debug log, try to connect to moode, and then attach the log here I might get an idea why. In any case the WAV header option won't work with Volumio or Moode.

**Comment by dheijl** [comment]
Question: did you enable the upnp client for mpd in the UPnP/DLNA section (follows the Renderer section) in Moode?

**Comment by RenEH01** [comment]
Hello, upnp renderer is enabled I’ve attached two pictures of the failure screen I’m receiving in Moode. 
![648CD69F-4B5E-4F5D-8F0F-68F75F53E2E5](https://user-images.githubusercontent.com/52057841/148651961-595d81f0-4953-4ebd-ab96-99280caed279.jpeg)
![AACD0515-F2A3-4B53-BE36-B0A7A070AC13](https://user-images.githubusercontent.com/52057841/148651965-b6376575-65a9-4b89-a939-cb43f978fd15.jpeg)

One of the screens is with the wave header enabled and the other is not. With a lot of fiddling I was able to get white noise coming from the renderer, I used directsound instead of wasapi in Kodi, but that was not the sound it should have been pushing from Kodi in windows. I was trying to stream flac audio from a video file.

**Comment by RenEH01** [comment]
Sorry, the second image is incorrect, the second image should of mentioned a curl error. I’ll try to get you the debug logs and proper error message later today.

**Comment by RenEH01** [comment]
Hello the curl error was only with the wav header enabled. So I don’t think it’s relevant in this case, however the above photos are the error message without the wav header.

**Comment by dheijl** [comment]
Without the debug log there's not much I can say.

But if Moode is anything like Volumio then
- wav header won't work
- 24 bit will produce nothing but noise
- chunked transfer is not recommended

**Comment by RenEH01** [comment]
Thank you for your assistance. With your settings I was able to get it running with Volumio, but there was a few limitations in my set up in comparison to tuneblade, similar software but airplay. I'll open a new and different issue and try to resolve this one if we can sort out the other one.

**Comment by JWolvers** [comment]
Hello, we just installed Moode Audio Player, we get the same error when trying to stream from SWYH-rs. I attached the debug log
[log.txt](https://github.com/dheijl/swyh-rs/files/7959152/log.txt)
.

**Comment by dheijl** [comment]
It looks like your Moode player is not configured for OpenHome Transport (the default for Volumio) but only for AV Transport, so swyh-rs falls back to using  AV Transport, but Moode responds with an internal server error 500 when setting the AV Transport URI : 

```
13:54:48 [DEBUG] (1) ureq::unit: sending request POST http://192.168.1.158:49152/uuid-5e211097-4658-5161-a661-b827eb2065eb/ctl-urn-schemas-upnp-org-service-AVTransport-1
13:54:48 [DEBUG] (1) ureq::unit: writing prelude: POST /uuid-5e211097-4658-5161-a661-b827eb2065eb/ctl-urn-schemas-upnp-org-service-AVTransport-1 HTTP/1.1
Host: 192.168.1.158:49152
Connection: close
User-Agent: swyh-rs-Rust/0.x
Accept: */*
SOAPAction: "urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI"
Content-Type: text/xml; charset="utf-8"
Content-Length: 1049
13:54:48 [DEBUG] (1) ureq::unit: response 500 to POST http://192.168.1.158:49152/uuid-5e211097-4658-5161-a661-b827eb2065eb/ctl-urn-schemas-upnp-org-service-AVTransport-1
13:54:48 [ERROR] <= SOAP POST error: http://192.168.1.158:49152/uuid-5e211097-4658-5161-a661-b827eb2065eb/ctl-urn-schemas-upnp-org-service-AVTransport-1: status code 500
```

I Have not yet used Moode, but might switch to it and ditch Volumio (as Volumio 3 seems to have serious problems while Volumio 2 is rock solid).

Do you have the possibility to configure OpenHome transport in Moode? If swyh-rs finds both transports it will always use OpenHome, and if you're lucky it will work. Both Volumio and Moode use upmpdcli as an upnp/dlna front-end for mpd, 

And perhaps Moode has an error log that you can check?

**Comment by dheijl** [comment]
Would you be able to test with the latest [1.3.22 release](https://github.com/dheijl/swyh-rs/releases/tag/1.3.23)? The DIDL-Lite for AV transport streamers was broken since 1.3.20 (it was OK for Openhome transport streamers).

**Comment by JWolvers** [comment]
I will test today or tomorrow.

**Comment by dheijl** [comment]
I have now tested with Moode 8.02. 

I can confirm that it works without any problem if:

- you configure the UPNP client for MPD as Openhome renderer (in Edit UPNP Config)
- and use the WAV header option.

**Comment by dheijl** [comment]
The new 1.4 release works with Moode without problems with the new flac support.
