### ISSUE TITLE
Possible to run this as command line to play specific audio file? 

### ISSUE THREAD

**Issue by Buster14** [dheijl/swyh-rs#58]
I just got a Sonos play one and i realized its almost impossible to redirect this as windows 10 speaker.
While I need to setup blueiris motion trigger to play alarm through speaker,
Fortunately it's also possible for Blueiris to trigger executable file when motion is triggered, 

So is it possible call with a command line, to run audio file played by sonos with this?

**Comment by dheijl** [comment]
I'm sorry but swyh-rs can not play sounds or audio files. It can only capture and stream audio that is already playing.
Perhaps you can call a script that first launches swyh-rs (with auto-reconnect active) followed by an audio player that plays your file?
