### ISSUE TITLE
Stream playback doesn't start on Libratone Zipp with 1.3.24

### ISSUE THREAD

**Issue by Chouffy** [dheijl/swyh-rs#59]
First, thanks for this nice piece of software! :)
Since the release 1.3.24, streaming my sound to a Libratone Zipp speaker doesn't work.

Here's what I do:
1. Make sure that the speaker is on
2. Make sure that I already stream some audio
3. Download and launch the 1.3.24 release on Windows 10 21H1 x64
4. Select the LTH Zipp speaker
5. Audio don't start and the following happen in the log:
![image](https://user-images.githubusercontent.com/9288966/166627024-08867835-bf42-4b19-994c-0d6e51875141.png)

With the previous version, it successfully works:
1. and 2. are the same
3. Download and launch the **1.3.23** release on Windows 10 21H1 x64
4. Select the LTH Zipp speaker
5. Enjoy good sounds - here's the log
![image](https://user-images.githubusercontent.com/9288966/166627165-90fd7471-50d9-4de1-a37e-da58b6c6af81.png)

Let me know if you need something else to debug this!

**Comment by dheijl** [comment]
I'm sorry but I seem to have broken AV transport (again). I only use Openhome transport renderers myself and I didn't test AV transport I'm afraid... I'll try to fix it asap.

**Comment by dheijl** [comment]
Fixed with the [1.25](https://github.com/dheijl/swyh-rs/releases/tag/1.3.25) release.

**Comment by Chouffy** [comment]
That was fast, it's indeed fixed for me! Thanks 😊
