### ISSUE TITLE
swyh but not swyh-rs streams to receiver

### ISSUE THREAD

**Issue by c2b2pss** [dheijl/swyh-rs#61]
Hi,

Firstly, thanks for offering the option of streaming higher res audio on Swyh and really improving the upnp options to stream system-wide audio available on windows!

I am running Windows 11.  Swyh generic works for my receiver -- my receiver sees Swyh as "media server" and I can select and stream my Windows audio.

However, Swyh-res does not show up as a streaming server on my receiver.  It is not seen at all.  

BUT, on the Swyh-res on my PC it does show the receiver under "Upnp Rendering Devices on port..."  - but choosing it thru Swyh-res causes it show 'start.....' and then 'stop....'.  

```
AV Start playing on Integra DRX-7.1 4FCD45 host=192.168.1.40 port=8888 from 192.168.1.250 using AvTransport Play
AV Stop playing on Integra DRX-7.1 4FCD45 host=192.168.1.40 port=8888
```
None of this happens with generic Swyh.

Any ideas?

Thanks!

**Comment by dheijl** [comment]
I suppose the Onkyo does not understand the streaming format (audio/l16, naked lpcm), so it does not start streaming.

Did you try with the "WAV" header option enabled?

**Comment by c2b2pss** [comment]
After much testing, this does look like an LPCM issue, although per my receiver LPCM 16/44.1 audio must work.  WAV does work.  

Using foobar2000 I am able to get wav at 24/192khz. It requires many things to set up, and is not a simple solution like swyh.....SO....

Is it possible to capture and send in native format? For example, if audio playing is 24/96 can we capture and stream as flac 24/96.  Most receivers do flac easily.  Are you using LPCM because it is "losless"?

**Comment by dheijl** [comment]
Many devices do not support "RAW" LPCM streams, that is why the "WAV" header option exists: it simply adds a dummy WAV header to that same "RAW" LPCM stream, so your device is receiving the original PCM inside a "WAV" envelope.

swyh-rs does not do any transcoding or resampling of the captured audio, so the quality of the captured stream is always preserved.

I have considered encoding to lossless FLAC, but unfortunately there is no rust language implementation of the FLAC encoder at this moment.

If you are capturing 24/96 on your PC swyh-rs will send 16/96 LPCM to your receiver, with or without WAV header. 

I have found that most devices do not support 24 bit when streaming raw LPCM, you can try enabling 24 bit in swyh-rs but you will probably only get noise. I could only get 24 bit LPCM to work when streaming to Bubble/upnp, not to actual devices, I suspect a problem with the HTTP headers but have been unable to find a solution.  This would be solved if I could encode to FLAC.

**Comment by dheijl** [comment]
I am closing this since it works with the WAV header, but Flac support remains on my todo list.

**Comment by dheijl** [comment]
Version 1.4.0 should support FLAC (16 and 24 bit).
