### ISSUE TITLE
Sonos Track Not Encoded Correctly

### ISSUE THREAD

**Issue by dkillough** [dheijl/swyh-rs#62]
Hi all, 

I've been trying to transmit my Win10 desktop audio to a new Sonos speaker through swyh-rs.

Installing via the Setup executable of the most recent release (v.1.3.26) gives me the error "the track is not encoding correctly". #38 + online forums seems to point to a firewall issue, but checking out Windows Defender Firewall and manually allowing it on my network doesn't appear to change anything. UPnP is enabled on my router however I'm not sure if there are additional port forwarding rules I need to set up.

Running the program via the direct executable originally wouldn't connect to the IP:Port at all. Logs showed AV Start playing on my speaker and then immediately AV Stop being called. This led me to believe that the other service was still running in the background, which I confirmed via force quitting all related applications and playing back another track via Spotify directly on the speaker. Restarting swyh-rs now gives the "track not encoding correctly" error a la #30 and same as previous. 

I've also added a radio station via the sonos app on http://192.168.86.39:5901/stream/swyh.wav pulled from logs (below).

If someone more familiar with the project could help me out here that'd be much appreciated. Lmk if you need any further information. 

```Configuration { server_port: Some(5901), auto_resume: false, sound_source: "Headphone (Realtek(R) Audio)", log_level: Info, ssdp_interval_mins: 1.0, auto_reconnect: false, disable_chunked: false, use_wave_format: false, bits_per_sample: Some(16), monitor_rms: true, last_renderer: "SYMFONISK Bookshelf Bedroom - SYMFONISK Bookshelf Media Renderer", last_network: "192.168.86.39", config_dir: "C:\\Users\\piebl\\.swyh-rs" }
Setup audio sources
Now running at ABOVE_NORMAL_PRIORITY_CLASS
Capturing audio from: Headphone (Realtek(R) Audio)
Default audio SupportedStreamConfig { channels: 2, sample_rate: SampleRate(48000), buffer_size: Unknown, sample_format: F32 }
Discover networks
Starting SSDP discovery
The wave_reader is now receiving samples
The streaming server is listening on http://192.168.86.39:5901/stream/swyh.wav
Sample rate: 48000, sample format: audio/L16 (PCM)
AV Start playing on Bedroom - SYMFONISK Bookshelf Media Renderer host=192.168.86.51 port=1400 from 192.168.86.39 using AvTransport Play
AV Stop playing on Bedroom - SYMFONISK Bookshelf Media Renderer host=192.168.86.51 port=1400
Received request /stream/swyh.wav from 192.168.86.51:35560
Streaming audio/L16 (LPCM), input sample format F32, channels=2, rate=48000, disable chunked=false to 192.168.86.51:35560
Streaming to 192.168.86.51:35560 has ended
```

**Comment by dheijl** [comment]
Sonos needs the WAV header enabled, have you tried that?

**Comment by dkillough** [comment]
that worked immediately how did i not see that option

thanks

**Comment by dheijl** [comment]
You're welcome!

**Comment by dheijl** [comment]
The new 1.4 release now also supports flac (16 and 24 bit).

**Comment by dkillough** [comment]
Good to know! Thanks for your hard work on the project!
