### ISSUE TITLE
FLAC 24 Bit has much lower latency than other codecs

### ISSUE THREAD

**Issue by Silun** [dheijl/swyh-rs#66]
Hey there,

during the testing for https://github.com/dheijl/swyh-rs/issues/65 I have noticed something else:

In the same test setup as described in that other ticket, the latency for LPCM, WAV, and FLAC 16 Bit is about the same when playing from the same machine (and thus avoiding any network latency). However, FLAC in 24 Bit mode has reproducibly much lower latency. I'd say about 0.5 seconds vs. 1.0 - 1.5 seconds. Although that is quite weird, it is also really awesome! The better latency is much appreciated!

I was thinking it might be due to my player's different buffer sizes for WAV vs FLAC streams, but then again FLAC 16 Bit is as delayed as WAV and not quick like FLAC 24 Bit.

Edit: OK, I believe it is not necessarily a feature of FLAC, but of the 24 Bit checkbox. It said that 24 Bit would only work correctly with FLAC so I didn't test it fully before opening the ticket. My bad.

- swyh-rs with 24 Bit checked will have low latency.
- swyh-rs with 16 Bit will always have longer latency.
- The actual audio bitness coming out of the player or configured in VB-Audio does not seem to matter, so it's probably not due to conversion.

**Comment by dheijl** [comment]
24 bit uses up more buffer space than 16 bit, both in the OS and in the player. So the buffers fill up more quickly reducing the latency (I guess).

**Comment by dheijl** [comment]
I'll close this as I don't think that any action is required here.
