### ISSUE TITLE
Swyh-rs won't start in windows 11

### ISSUE THREAD

**Issue by konyong** [dheijl/swyh-rs#69]
i don't know what happen, it's suddenly won't start. i have uninstal and instal it.

**Comment by dheijl** [comment]
Please use the zip file with the debug exe, if you run that you should get a console window with debug output that tells you what's wrong.

**Comment by konyong** [comment]
i can't start the debug too. but when i change to other user account, i can start swyh-rs. i wonder what's wrong.

**Comment by dheijl** [comment]
Something may have corrupted your configuration file. You can safely delete it: `C:\Users\{your_user_name}\.swyh-rs\config.toml`.
If there is a non-empty `log.txt` in that folder could you attach it to your reply here ?

**Comment by konyong** [comment]
Thank you @dheijl  i delete config.toml and it works like magic, thank you so much.

here is the log file
[log.txt](https://github.com/dheijl/swyh-rs/files/9305778/log.txt)

**Comment by konyong** [comment]
Thank you @dheijl i delete config.toml and it works like magic, thank you so much.

here is the log file
[log.txt](https://github.com/dheijl/swyh-rs/files/9305778/log.txt)

**Comment by dheijl** [comment]
Is probably fixed with [1.4.4](https://github.com/dheijl/swyh-rs/releases/tag/1.4.4)
