### ISSUE TITLE
Duplicate named audio sources break UI

### ISSUE THREAD

**Issue by dkillough** [dheijl/swyh-rs#70]
PREVIOUS TITLE: Last Audio Source Not Selectable

Hi,

I've been using SWYH-rs daily since my last message (#62) using the same audio source. I decided to change it today, but do not seem to be able to set it back. I get the "Configuration Value Changed!" prompt to restart the app, but the actual audio source doesn't seem to change for that device in particular. 

My (unfounded) suggestion would be to check for an off-by-one error in the [Audio Source call](https://github.com/dheijl/swyh-rs/blob/master/src/ui/mainform.rs#L173), but that could just be a coincidence. Sorry I'm not being of more help diagnosing the issue!

I've recorded a video as that's probably a better demonstration: https://youtu.be/o1EySN72X4o

Previously using release 1.3.26 (I think) -- uninstalled and reinstalled latest release (1.4.3) which is the version on video above.

Thank you & let me know if I can provide any further information!

**Comment by dkillough** [comment]
(The app still works just fine when selecting another option, i.e. Rift Audio, then playing to speakers from there)

**Comment by dkillough** [comment]
actually i figured out what the problem is:

Reading debug logs, it seems that selecting the speakers that I want actually changes to the wrong audio source. 
![image](https://user-images.githubusercontent.com/52042713/184574053-2aa6626d-9ae8-49f1-b624-2425d384bd23.png)

The reason for this is that I have two monitors named the same thing (S2719DGF) as they are the same model. Both of these have a headphone output that I don't use, but they're still listed as output options in Windows sound devices. 

Disabling one of these monitor options fixes the issue, and I can now re-select the speakers that I want. 
![image](https://user-images.githubusercontent.com/52042713/184574285-4f952b81-921f-4ba5-a19a-44bad48def4b.png)
![image](https://user-images.githubusercontent.com/52042713/184574217-e839b3bf-3ecd-427a-814c-2433f2ca4a0e.png)
![image](https://user-images.githubusercontent.com/52042713/184574182-266feb62-4cc3-4bfe-baef-4468d8423b48.png)

Therefore, I think the real issue is that the UI is pulling from an index of audio devices, and in skipping over the duplicate name entry it doesn't re-map the index that it skipped. Instead, the duplicate-named audio device should still be listed, allowing both to be selected.

**Comment by dheijl** [comment]
When the app starts it uses the audio device name that was saved in the config file, the index in the device list is not used. In the presence of duplicates names that is obviously going to be a problem.
Using an index could be an even bigger problem if Windows rearranges the devices or if the user removes or disables devices.
Perhaps using both in case of duplicates is an option to consider.

**Comment by dheijl** [comment]
Could you check if the new [1.4.4 beta](https://github.com/dheijl/swyh-rs/releases/tag/1.4.4-beta1) fixes it?

**Comment by dheijl** [comment]
Should be fixed in [1.4.4](https://github.com/dheijl/swyh-rs/releases/tag/1.4.4)
