### ISSUE TITLE
FLAC support for Sonos?

### ISSUE THREAD

**Issue by Max3651** [dheijl/swyh-rs#73]
No matter what I’ve tried, FLAC doesn’t work on Sonos. This isn’t really an issue but I do feel if you can find a workaround it can help lower the latency and bring native 24 bit support as .wav gets downscaled to 16 bit with Sonos speakers.

**Comment by dheijl** [comment]
The problem is that I don't have Sonos, so I can't test/debug this issue to try and find a solution...

**Comment by dheijl** [comment]
Sonos does not support flac over dlna, so I am closing this.
