### ISSUE TITLE
[Feature request] Volume setting

### ISSUE THREAD

**Issue by ngsmg** [dheijl/swyh-rs#79]
Would it be possible to add an option for volume setting in the app? Maybe even with a checkbox to mirror volume % from the streamed audio output device from Windows? Maybe also with a checkbox to match the volume both ways, so if I change the volume on the DLNA device, that would also affect system volume in windows on the output device? I ask as the volume bar works perfectly both ways (from pc to DLNA device and vice versa) in Windows' cast app if I natively stream a file from Windows 10.

**Comment by dheijl** [comment]
I'm very sorry but it won't happen. Swyh-rs only implements the absolute minimum of the DLNA protocol to allow it to stream. Everything else like status report callbacks and commands like set volume etc... are left to the dlna controllers supplied (or not) by the manufacturers of the receivers. Things would be different  if a Rust dlna library were available, but I don't think there is much interest for that. DLNA is not "hot" I'm afraid...

**Comment by dheijl** [comment]
The latest release 1.9.5 now has volume sliders.
