### ISSUE TITLE
Can you add input source ?

### ISSUE THREAD

**Issue by MX10-AC2N** [dheijl/swyh-rs#8]
Hi again,

Would it be possible to add an option to choose the audio input source?

My problem I want to keep my native sound card as default audio source and use VB-Audio Hifi only for my web browser and my deezer app.
With the sound settings of windows 10 you can choose the audio input and output source by application but it does not work with swyh-rs, so if it is not too complicated to add the option to select Input source that would be a good option
I would point out that with LocalAudioBroadcast which also has no option to select the audio input source, I was able to change the audio input source via the sound settings of windows and therefore completely separate the sounds on my pc and what I send in streaming ..
A new field of research..

**Comment by MX10-AC2N** [comment]
![Capture d’écran (3)](https://user-images.githubusercontent.com/62643837/95588304-8d9e9900-0a43-11eb-909a-3a8f5ac67b76.png)

**Comment by dheijl** [comment]
It's certainly possible to add the input source, it's just a bit of work so it won't be for tomorrow morning.

And as for the "silence" problem, I'll check if it's possible to specify a track length, if yes I could set it to "infinity" or a very large value in the hope that the HK won't try to detect song boundaries because of the absence of a track length.

**Comment by MX10-AC2N** [comment]
> It's certainly possible to add the input source, it's just a bit of work so it won't be for tomorrow morning.
Of course, however I wonder why it is not possible to choose audio in / out via windows settings, when it works fine with LocalAudioBroadcast ..
![Capture d’écran (4)](https://user-images.githubusercontent.com/62643837/95651778-d78f8980-0aec-11eb-91f9-bb0e0aaed6fc.png)

**Comment by MX10-AC2N** [comment]
![Capture d’écran (5)](https://user-images.githubusercontent.com/62643837/95652392-e8da9500-0af0-11eb-9dff-4c885b90c331.png)

**Comment by dheijl** [comment]
Swyh-rs is crossplatform, it runs on Windows and on Linux. It can only use things that work on both platforms. I'll try to find out if I can detect this setting on both platforms...

**Comment by dheijl** [comment]
I see that Windows does not remember this setting after I close and restart swyh-rs.

So I would prefer to let you choose the sound source in swyh-rs and store the setting in a preferences file.  This should work on Windows and on Linux.

What do you think?

**Comment by MX10-AC2N** [comment]
In fact, to remain cross-platform, it will be easier to have the parameter integrated directly into swyh-rs.
My solution with the windows settings is obviously only valid under this OS

**Comment by MX10-AC2N** [comment]
> I see that Windows does not remember this setting after I close and restart swyh-rs.

On my pc this setting is always active when I close and restart any software, with swyh-rs too..

**Comment by dheijl** [comment]
I could try to detect this setting on Windows, but I don't know if the cpal library supports this. Anyway, if you can set it once in swyh-rs and then forget about it it should be OK too I think.

**Comment by dheijl** [comment]
Yes, it should be easy to just send a new (silent) play command when the renderer disconnects.

**Comment by dheijl** [comment]
If you want to test:

https://github.com/dheijl/swyh-rs/releases/tag/0.8.4

You have to rerstart the application to activate the new source.

**Comment by MX10-AC2N** [comment]
Hello Dheijl, I just tested v0.8.4. Input source selection works but I get a sound that is not clean it's weird ..
See the debug 

Supported hosts:
  [Wasapi]
Available hosts:
  [Wasapi]
WASAPI
  Default Output Device:
    Some("Speakers (Intel SST Audio Device (WDM))")
  Devices:
  1. "Speakers (Intel SST Audio Device (WDM))"
    All supported output stream configs:
      1.1. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(48000), max_sample_rate: SampleRate(48000), buffer_size: Unknown, sample_format: F32 }
    Default output stream config:
      SupportedStreamConfig { channels: 2, sample_rate: SampleRate(48000), buffer_size: Unknown, sample_format: F32 }
  2. "Hi-Fi Cable Input (VB-Audio Hi-Fi Cable)"
    All supported output stream configs:
      2.1. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
    Default output stream config:
      SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
  3. "Microphone (Intel SST Audio Device (WDM))"
  4. "Hi-Fi Cable Output (VB-Audio Hi-Fi Cable)"
Current Configuration: Configuration { auto_resume: true, sound_source: "Hi-Fi Cable Input (VB-Audio Hi-Fi Cable)" }
Selected audio source: Hi-Fi Cable Input (VB-Audio Hi-Fi Cable)
log: SSDP discovery started
UDP response at 2012 from 192.168.1.26:56697:
HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
EXT:
LOCATION: http://192.168.1.26:80/dd.xml
SERVER: POSIX, UPnP/1.0, Intel MicroStack/1.0.2777
ST: urn:schemas-upnp-org:service:RenderingControl:1
USN: uuid:3dcc7100-f76c-11dd-87af-002261a59896::urn:schemas-upnp-org:service:RenderingControl:1


log: Renderer at : http://192.168.1.26:80/dd.xml
log: Getting renderer descriptions
Get service description for http://192.168.1.26:80/dd.xml
Service description:
<?xml version="1.0" encoding="utf-8"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:ms="urn:microsoft-com:wmc-1-0" xmlns:pnpx="http://schemas.microsoft.com/windows/pnpx/2005/11" xmlns:microsoft="urn:schemas-microsoft-com:WMPNSS-1-0" xmlns:df="http://schemas.microsoft.com/windows/2008/09/devicefoundation">
   <specVersion>
      <major>1</major>
      <minor>0</minor>
   </specVersion>
   <device ms:X_MS_SupportsWMDRM="true">
      <deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
      <presentationURL>/web</presentationURL>
<pnpx:X_hardwareId>VEN_2A2D&amp;DEV_0001&amp;SUBSYS_0001&amp;REV_01 VEN_0033&amp;DEV_0005&amp;REV_01</pnpx:X_hardwareId>
<pnpx:X_compatibleId>MS_DigitalMediaDeviceClass_DMR_V001</pnpx:X_compatibleId>
<pnpx:X_deviceCategory>MediaDevices</pnpx:X_deviceCategory>
<df:X_deviceCategory>Multimedia.DMR</df:X_deviceCategory>
<microsoft:magicPacketWakeSupported>0</microsoft:magicPacketWakeSupported>
<microsoft:magicPacketSendSupported>1</microsoft:magicPacketSendSupported>
      <dlna:X_DLNADOC xmlns:dlna="urn:schemas-dlna-org:device-1-0">DMR-1.50</dlna:X_DLNADOC>
      <friendlyName>Harman Kardon AVR265</friendlyName>
      <manufacturer>Harman Kardon</manufacturer>
      <manufacturerURL>http://www.harmankardon.com</manufacturerURL>
      <modelDescription>ir-ser-FS2026-0200-0149_V2.2.14.37060-10</modelDescription>
      <modelName>None</modelName>
      <modelNumber>None</modelNumber>
      <modelURL>http://www.radioharmankardon.com</modelURL>
      <serialNumber>0b04070303101f2701003e00ffff4dff</serialNumber>
      <UDN>uuid:3dcc7100-f76c-11dd-87af-002261a59896</UDN>
      <iconList>
         <icon>
            <mimetype>image/png</mimetype>
            <width>48</width>
            <height>48</height>
            <depth>32</depth>
            <url>/icon.png</url>
         </icon>
         <icon>
            <mimetype>image/jpeg</mimetype>
            <width>48</width>
            <height>48</height>
            <depth>32</depth>
            <url>/icon.jpg</url>
         </icon>
         <icon>
            <mimetype>image/png</mimetype>
            <width>120</width>
            <height>120</height>
            <depth>32</depth>
            <url>/icon2.png</url>
         </icon>
         <icon>
            <mimetype>image/jpeg</mimetype>
            <width>120</width>
            <height>120</height>
            <depth>32</depth>
            <url>/icon2.jpg</url>
         </icon>
      </iconList>
  <serviceList><service><serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType><serviceId>urn:upnp-org:serviceId:AVTransport</serviceId><SCPDURL>AVTransport/scpd.xml</SCPDURL><controlURL>AVTransport/control</controlURL><eventSubURL>AVTransport/event</eventSubURL></service><service><serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType><serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId><SCPDURL>ConnectionManager/scpd.xml</SCPDURL><controlURL>ConnectionManager/control</controlURL><eventSubURL>ConnectionManager/event</eventSubURL></service><service><serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType><serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId><SCPDURL>RenderingControl/scpd.xml</SCPDURL><controlURL>RenderingControl/control</controlURL><eventSubURL>RenderingControl/event</eventSubURL></service></serviceList></device></root>
log: Renderer Harman Kardon AVR265 None ip 192.168.1.26 at urlbase http://192.168.1.26:80/ has 3 services
log:   => OpenHome Playlist control url: '', AvTransport url: '/AVTransport/control'
.. urn:schemas-upnp-org:service:AVTransport:1 urn:upnp-org:serviceId:AVTransport /AVTransport/control
.. urn:schemas-upnp-org:service:ConnectionManager:1 urn:upnp-org:serviceId:ConnectionManager /ConnectionManager/control
.. urn:schemas-upnp-org:service:RenderingControl:1 urn:upnp-org:serviceId:RenderingControl /RenderingControl/control
log: SSDP discovery complete
Got 1 renderers
Try capturing system audio
log: Capturing audio from: Hi-Fi Cable Input (VB-Audio Hi-Fi Cable)
log: Default audio SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
log: The streaming server is listening on http://192.168.1.27:5901/stream/swyh.wav
log: The wave_reader is receiving samples
Supported hosts:
  [Wasapi]
Available hosts:
  [Wasapi]
WASAPI
  Default Output Device:
    Some("Hi-Fi Cable Input (VB-Audio Hi-Fi Cable)")
  Devices:
  1. "Speakers (Intel SST Audio Device (WDM))"
    All supported output stream configs:
      1.1. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(48000), max_sample_rate: SampleRate(48000), buffer_size: Unknown, sample_format: F32 }
    Default output stream config:
      SupportedStreamConfig { channels: 2, sample_rate: SampleRate(48000), buffer_size: Unknown, sample_format: F32 }
  2. "Hi-Fi Cable Input (VB-Audio Hi-Fi Cable)"
    All supported output stream configs:
      2.1. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
    Default output stream config:
      SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
  3. "Microphone (Intel SST Audio Device (WDM))"
  4. "Hi-Fi Cable Output (VB-Audio Hi-Fi Cable)"
Pushed renderer #0 None Harman Kardon AVR265, state = ON
log: AV Stop playing on Harman Kardon AVR265 host=192.168.1.26 port=80
url: http://192.168.1.26:80/AVTransport/control,
=>SOAP Action: urn:schemas-upnp-org:service:AVTransport:1#Stop,
=>SOAP xml:
<?xml version="1.0" encoding="utf-8"?><s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:Stop xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID></u:Stop></s:Body></s:Envelope>
<=SOAP response: <?xml version="1.0" encoding="utf-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:StopResponse xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"></u:StopResponse></s:Body></s:Envelope>

log: AV Start playing on Harman Kardon AVR265 host=192.168.1.26 port=80 from 192.168.1.27 using AvTransport Play
AvTransport server URL: http://192.168.1.27:5901/stream/swyh.wav
url: http://192.168.1.26:80/AVTransport/control,
=>SOAP Action: urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI,
=>SOAP xml:
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:SetAVTransportURI xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID><CurrentURI>http://192.168.1.27:5901/stream/swyh.wav</CurrentURI><CurrentURIMetaData>&lt;DIDL-Lite xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot;&gt;&lt;item id=&quot;1&quot; parentID=&quot;0&quot; restricted=&quot;0&quot;&gt;&lt;dc:title&gt;swyh-rs&lt;/dc:title&gt;&lt;res bitsPerSample=&quot;16&quot; nrAudioChannels=&quot;2&quot; protocolInfo=&quot;http-get:*:audio/l16;rate=48000;channels=2:DLNA.ORG_PN=LPCM&quot; sampleFrequency=&quot;48000&quot; duration=&quot;0&quot; &gt;http://192.168.1.27:5901/stream/swyh.wav&lt;/res&gt;&lt;upnp:class&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;</CurrentURIMetaData></u:SetAVTransportURI></s:Body></s:Envelope>
<=SOAP response: <?xml version="1.0" encoding="utf-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:SetAVTransportURIResponse xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"></u:SetAVTransportURIResponse></s:Body></s:Envelope>

url: http://192.168.1.26:80/AVTransport/control,
=>SOAP Action: urn:schemas-upnp-org:service:AVTransport:1#Play,
=>SOAP xml:
<?xml version="1.0" encoding="utf-8"?><s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:Play xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID><Speed>1</Speed></u:Play></s:Body></s:Envelope>
<=SOAP response: <?xml version="1.0" encoding="utf-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:PlayResponse xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"></u:PlayResponse></s:Body></s:Envelope>

log: Received request /stream/swyh.wav from 192.168.1.26:50008
Pushed renderer #0 None Harman Kardon AVR265, state = OFF
log: AV Stop playing on Harman Kardon AVR265 host=192.168.1.26 port=80
url: http://192.168.1.26:80/AVTransport/control,
=>SOAP Action: urn:schemas-upnp-org:service:AVTransport:1#Stop,
=>SOAP xml:
<?xml version="1.0" encoding="utf-8"?><s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:Stop xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID></u:Stop></s:Body></s:Envelope>
<=SOAP response: <?xml version="1.0" encoding="utf-8"?>
<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:StopResponse xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"></u:StopResponse></s:Body></s:Envelope>

log: =>Http connection with 192.168.1.26:50008 terminated [Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte. (os error 10053)]
log: Streaming to 192.168.1.26:50008 has ended
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 18446744073709551615', src\main.rs:318:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by MX10-AC2N** [comment]
Another small detail, the selection of the input source is at the same level as the autoresume play box in the GUI, which is not very clear..
![Capture d’écran (6)](https://user-images.githubusercontent.com/62643837/95951000-e9777200-0df5-11eb-9d95-cbb069780681.png)

**Comment by MX10-AC2N** [comment]
I think I found out where this problem came from.
If I run swyh-rs with VB-Audio as the default audio device in windows, I have no problem.
If I run swyh-rs with my real default sound card in windows (Speakers intel SST Audio Device WDM) and choose VB-Audio as the audio source for swyh-rs I have my problem with the sound ..
My sound card is by default in 48000 and not in 44100 maybe the problem comes from there ..
I will try by setting VB-Audio to 48000 to see if I still have this problem ...

**Comment by MX10-AC2N** [comment]
Yes that's it if I configure VB-Audio in 48000 I don't have any more problems in the sound. It is curious it seems that it is necessary that VB-Audio is configured like the real sound card ??

**Comment by MX10-AC2N** [comment]
Congratulations, it seems to be on the right track, great performance ..!
I have a small request, can you add as you did on swyh, priority access to resources so as not to have a slowdown in the stream when I do other things on my pc..
You need to give a minimal size for GUI. ;-)

![Capture d’écran (7)](https://user-images.githubusercontent.com/62643837/95954542-c3ed6700-0dfb-11eb-9755-a6e4871985b8.png)

**Comment by dheijl** [comment]
Thanks for the testing, the feedback and the suggestions!

> thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 18446744073709551615', src\main.rs:318:28
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

 => a bug, fixed
> Another small detail, the selection of the input source is at the same level as the autoresume play box in the GUI, which is not very clear..

=> noted, will fix

> Yes that's it if I configure VB-Audio in 48000 I don't have any more problems in the sound. It is curious it seems that it is necessary that VB-Audio is configured like the real sound card ??

=>HiFi cable does not do any resampling, it takes what it gets from Windows and passes this on without any interference, unlike real soundcards that try to "enhance" the sound and do automatic resampling etc... So yes, you have to configure VBAudio the same sampling rate as the Windows default rate. If you're playing DVD's that means 48000 Hz is optimal, if playing CD quality (like Deezer, Spotify Premium) 44100 Hz is best to avoid resampling by Windows.

> I have a small request, can you add as you did on swyh, priority access to resources so as not to have a slowdown in the stream when I do other things on my pc..

=> OK will do

> You need to give a minimal size for GUI. ;-)

=> You're right, but I hate GUI programming!

**Comment by dheijl** [comment]
New release: https://github.com/dheijl/swyh-rs/releases/tag/0.8.5.

The minimum GUI size is not implemented yet...

**Comment by MX10-AC2N** [comment]
Thanks a lot for all you do.. I try v0.8.6... Work great..!!
I can't modify to 44100 my real sound card, the parameter is grayed out ... 48000 it's good too..!
