### ISSUE TITLE
EXE file inside linux bundle

### ISSUE THREAD

**Issue by apss-pohl** [dheijl/swyh-rs#80]
Hi,
i noticed that inside the linux build there is an .exe file. Is that expected?
https://github.com/dheijl/swyh-rs/releases/download/1.4.5/swyh-rs-deb.zip

Best regards

**Comment by dheijl** [comment]
There is no Linux bundle (yet). Only a Windows set-up and a zip file with a 64bit Windows exe and another one with a 64bit Windows debug build exe. I'd like to provide a universal Linux musl build, but one of the libraries I use prevents it.

**Comment by apss-pohl** [comment]
Ok, i got mixed up with the name of the zip. I was assuming the ".deb" should indicate a debian software package.

**Comment by dheijl** [comment]
I see, I'll change the deb to debug in future releases. Sorry for causing the confusion!

**Comment by dheijl** [comment]
I added a Linux Mint 21 (Ubuntu 22.04.1 LTS) build to the current release, I don't know if it will run on other Debian bases releases.

**Comment by apss-pohl** [comment]
FYI: Just tried the appimage, working fine!

**Comment by dheijl** [comment]
Thanks for lettong me know!
