### ISSUE TITLE
SWYH-RS config.toml location and simultaneous sessions.  

### ISSUE THREAD

**Issue by cavadias** [dheijl/swyh-rs#82]
Hello,
First of all thank you for everything, 
I need to run two different sessions / configurations on the same windows system. (with autostart).
Individual configuration edit/save works fine with both running sessions working properly.  When the program is closed the last configuration runs (config.toml). Could there be a work around of the save location of the config.toml? Be on the same folder with the executable instead on the profile?

Thank you.

**Comment by cavadias** [comment]
Hi, 
Yes the instance feature is what it need, since I have two captrure sources, feeding two different ports.
The command line parameter is not working for me. Is it a working feature?

Thank you very much!

**Comment by dheijl** [comment]
The command line feature is something that I will add in the next release to enable your usage scenario, hopefully this weekend.

**Comment by dheijl** [comment]
I published a new [1.5.0 prererelease](https://github.com/dheijl/swyh-rs/releases/tag/1.5.0), does it solve your problem?

**Comment by cavadias** [comment]
Thank you very much! Now I have two sessions starting up correctly with their settings!
It works great!!!
