### ISSUE TITLE
Unable to send stream from shairport / Airplay 2

### ISSUE THREAD

**Issue by alexander-alvarez** [dheijl/swyh-rs#86]
### First of all thanks for this. It's beautiful and exactly what I was looking for when hacking around.

This is most likely user error, since I have moderate understanding knowledge of audio, but if you're kind enough to read and help out, I'm sure it'll make a nice use case that I'd be happy to document when I get it working.

I have a [shairport-sync](https://github.com/mikebrady/shairport-sync) server that is properly running and can send Airplay 2 streams to any audio device on my Ubuntu 22.0 server . As a test when I send it to the headphone jack / DAC I get noise. :+1: 

My plan was to setup a loopback interface and instead of pointing the shairport audio output to the DAC, pointing the output stream to the loopback, and then having `swyh-rs` have that loopback interface as in input.

I've downloaded a .wav file and managed to play it through my loopback interfacve, and have `swyh-rs` (latest appimage) pick it up and stream it to my Sonos system. :+1: 
example command:
```sh
aplay -D plughw:CARD=Loopback,DEV=0 StarWars60.wav
Playing WAVE 'StarWars60.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
```

Now, putting the two together yield nothing coming through on `swyh-rs`, and somehow while tweaking and tuning things I managed to break the ability to send the wav file through the loopback and have it work on Sonos. :-1: 

I believe I have to do some recoding / resampling since Airplay 2 can be encoded in 256kbps AAC, and as you've highlighted Sonos is limited to 48KHz 16 bit anyway. And I'd have to have it be WAV format. idk if there's some DRM protection or whatnot I'd have (or be unable to get around).

Anyways...
Is this what I'm trying to accomplish completely far-fetched?
Are there easier ways of achieving this that I'm completely missing? (like sticking a cable from the headphone jack to the microphone and then having `swyh-rs` read from the microphone input :joy:)

**Comment by dheijl** [comment]
Did you check in pavucontrol that the monitor is enabled for the device that is playing?  If not swyh-rs can not capture the audio. 
I use a device that is not actually connected for playback on Linux when using swyh-rs, and have never tried loopback.

**Comment by alexander-alvarez** [comment]
@dheijl thanks for the rec!! I have it working now. I rebuilt shairport-sync supporting pulseaudio instead of just alsa and now when opening pavucontrol I  see "alsa plug-in [swyh-rs]: " which i can set to the monitor of my pulse audio / "built in analog stereo and music is streaming.

I'll poke around the repo to see how I can run this in a headless fashion to bundle it up nicely. Let me know if you want me to contribute docs somewhere for my set up

**Comment by dheijl** [comment]
I agree that a cli version would be nice to have. But I have not really thought about the implications...
