### ISSUE TITLE
Not a bug. Sponsorship

### ISSUE THREAD

**Issue by boydfields** [dheijl/swyh-rs#90]
Hello, I would like to show my appreciation and send you a small tip for your amazing work on creating this application. I cannot locate any details to send you PayPal donation. My email is boyd@boydfields.com. Regards, Boyd.

**Comment by dheijl** [comment]
Thanks for the kind words but I do this purely for my own pleasure and so no sponsorship is needed.
It's always nice to hear that some people find it useful though!
