### ISSUE TITLE
Long start delay

### ISSUE THREAD

**Issue by lucalewin** [dheijl/swyh-rs#91]
Hi, first of all, this project is fantastic.

I'm currently using this with my Sonos speakers.

The issue I am having is a long delay (~4-5s) between starting a video (on Youtube) and the sound getting played.
This only happens when there is silence before playing the audio. The delay between video and audio when playing is minimal (~0.5s)

**Comment by dheijl** [comment]
Thanks! But I'm afraid you can't have your cake and eat it: if you're using the "play silence" option to prevent disconnection in the absence of sound, you have to wait until the Sonos has finished playing the "silence" still in its receive buffer. AFAIK there is no way that swyh-rs can clear that buffer on the S)onos side, except by you toggling the button for the Sonos in swyh-rs (and thus sending the "stop play", "clear playlist", "load playlist" and "start play" commands to the Sonos).

**Comment by dheijl** [comment]
I did some tests using WAV 16 bit 44 kHz and silence, but was not able to get a delay above 1 second.

This is the setting I used in my _config.toml_:

```
CaptureTimeout = 250
InjectSilence = true
```

But I don't have Sonos, perhaps that's the difference.

**Comment by lucalewin** [comment]
Yesterday I got a delay above 10sec. I just switched between Youtube videos.
I'll try to test it with your settings today.

One thing I thought of is reducing the size of the silence buffer. Could that maybe decrease the delay?

**Comment by dheijl** [comment]
The size of the silence buffer is based on the value of the capture timeout, if you decrease the capture timeout you atomatically get a smaller silence buffer.

**Comment by lucalewin** [comment]
It took a bit longer than expected, but I finally looked at the config file.
It looked like this:
```
CaptureTimeout = 2000
InjectSilence = false
```

I then changed it to your settings and now the delay is between 500ms and 1s. Much better.
Are the settings I had the default settings? Because I'm sure that I did not change them myself

**Comment by dheijl** [comment]
They are indeed the default settings. Glad to hear that it's better now!

**Comment by dheijl** [comment]
I suppose I can close this now.
