### ISSUE TITLE
Flac streaming don't work on Sonos Amp Gen 2

### ISSUE THREAD

**Issue by dawnarius** [dheijl/swyh-rs#92]
I am trying to stream from windows to Sonos amp gen 2 and only the WAV format is working (both 16 and 24 bit)
FLAC Format didn't work in 16 nor in 24 bit, the connection ends as soon as it starts (no sound at at all)
LPCM don't work neither
Here's the log for the FLAC attempt (it continues in a loop when autoreconnect and autoresume are enabled)
By the way, I suggest that you add timetamps in log

`Configuration { server_port: Some(5901), auto_resume: true, sound_source: "Headphones (Realtek(R) Audio)", sound_source_index: Some(1), log_level: Debug, ssdp_interval_mins: 10.0, auto_reconnect: true, disable_chunked: false, use_wave_format: false, bits_per_sample: Some(24), streaming_format: Some(Flac), monitor_rms: true, capture_timeout: Some(2000), inject_silence: Some(false), last_renderer: "Sonos Amp MY AMP - Sonos Amp Media Renderer", last_network: "192.168.1.2", config_dir: "C:\\Users\\TEST\\.swyh-rs", config_id: Some("") }`

`Setup audio sources`

`Now running at ABOVE_NORMAL_PRIORITY_CLASS`

`Capturing audio from: Headphones (Realtek(R) Audio)`

`Default audio SupportedStreamConfig { channels: 2, sample_rate: SampleRate(48000), buffer_size: Range { min: 0, max: 4294967295 }, sample_format: F32 }`

`Discover networks`

`Starting SSDP discovery`

`The wave_reader is now receiving samples`

`The streaming server is listening on http://192.168.1.2:5901/stream/swyh.wav`

`Streaming sample rate: 48000, bits per sample: 24, format: FLAC`

`Received request /stream/swyh.wav from 192.168.1.9:48766`

`Streaming audio/FLAC, input sample format F32, channels=2, rate=48000, disable chunked=false to 192.168.1.9:48766`

`Streaming to 192.168.1.9:48766 has ended`

`AV Start playing on MY AMP - Sonos Amp Media Renderer host=192.168.1.9 port=1400 from 192.168.1.2 using AvTransport Play`

`AV Stop playing on MY AMP - Sonos Amp Media Renderer host=192.168.1.9 port=1400`

`Received request /stream/swyh.wav from 192.168.1.9:48768`

`Streaming audio/FLAC, input sample format F32, channels=2, rate=48000, disable chunked=false to 192.168.1.9:48768`

`Streaming to 192.168.1.9:48768 has ended`

**Comment by dheijl** [comment]
Thanks for the suggestion.
If you want to see a detailed log with timestamps you only need to consult the logfile.
Sonos does not support flac when using dlna.
This and other stuff is clearly stated in the readme.

**Comment by dheijl** [comment]
Thanks for the nice words!

**Comment by dheijl** [comment]
The latest Sonos firmware seems to play FLAC with the current version of swyh-rs!

**Comment by dawnarius** [comment]
Yes I can confirm it's working great on my Sonos Amp Gen 2
Thank you very much
