### ISSUE TITLE
CLI version

### ISSUE THREAD

**Issue by lemascaret** [dheijl/swyh-rs#93]
Hello!
Could a CLI-only version be made available? 
Would be usefull on small headless servers..
Thks!

**Comment by dheijl** [comment]
The cli binary is on its way, but it might take some time.
The split into 2 binaries is complete, the GUI version works the same as before, but the CLI version is still an emtpy shell...
I have to design the commandline options now to allow you to configure the app first. You would start from a default config, where each option you specify changes a value in the existing config. No options would start thye app with the current (latest) config.
What do you think?

**Comment by lemascaret** [comment]
Well, the idea is to have a headless server running swyh-rs. The config file might be generated via a desktop-enabled computer on the same network to serve as a base for the cli version, which could be quiet sufficient to fulfill the goal. That could be a good hassle-free start?

**Comment by dheijl** [comment]
You'll be able to generate the config file settings with commandline options. And this will be persistent, so once the config is to your liking you can run without any options. At least that is what I'll try to implement.

**Comment by dheijl** [comment]
The cli version is working now, I'll prepare an new release later today or tomorrow. 
Only thing missing: autoreconnect to the last used player if you don't specify a player on the commandline.

Everything is controlled with command line options:

```sh
swyh-rs-cli.exe -p 5901 -l info -s 1 -i 10 -b 16 -r false -a true -d true -u true -o 192.168.0.129 -e 192.168.0.135 -f flac -h

Recognized options:
    -h (--help) : print usage
    -c (--config_id) string : config_id [_cli]
    -p (--server_port) u16 : server_port [5901]
    -a (--auto_reconnect) bool : auto reconnect [true]
    -r (--auto_resume) bool : auto_resume [false]
    -s (--sound_source) u16 : sound_source index [os default]
    -l (--log_level) string : log_level (info/debug) [info]
    -i (--ssdp_interval) i32 : ssdp_interval_mins [10]
    -d (--disable_chunked) bool : disable_chunked encoding [true]
    -b (--bits) u16 : bits_per_sample (16/24) [16]
    -f (--format) string : streaming_format (lpcm/flac/wav) [LPCM]
    -o (--player_ip) string : the player ip address [last used player]
    -e (--ip_address) string : ip address of the network interface [last used]

Args { config_id: None, server_port: Some(5901), auto_resume: Some(false), sound_source_index: Some(1), log_level: Some(Info), ssdp_interval_mins: Some(10.0), auto_reconnect: Some(true), disable_chunked: Some(true), use_wave_format: None, bits_per_sample: Some(16), streaming_format: Some(Flac), player_ip: Some("192.168.0.129"), ip_address: Some("192.168.0.135") }
```

**Comment by dheijl** [comment]
You can try the new prerelease [1.7.0-beta](https://github.com/dheijl/swyh-rs/releases/tag/1.7.0-beta)

**Comment by dheijl** [comment]
The new [1.7.0 CLI version](https://github.com/dheijl/swyh-rs/releases/tag/1.7.0) is now released, so I'll close this.

If you have any problems using it please open a new issue.
